MSG LEFT BY: DOCTOR WHO
DATE POSTED: FRI MAR  3  2:52:40 PM

TO CRACK CRISIS MOUNTAIN:

BOOT DOS 3.3
 CALL-151
 B925:18 60
 B988:18 60
 BE48:18
 B942:18
 BAAA:00
 RUN COPYA
COPY CRISIS MOUNTAIN
WITH A SECTOR EDITOR MAKE THE FOLLOWING
CHANGES ON TRACK 0 SECTOR 5
    24:D5 (WAS EB)
    2D:AA (WAS D5)
    36:96 (WAS AA)

NOW ITS CRACKED

ANOTHER CRACK FROM-

------------=> DOCTOR WHO <=-----------


MSG LEFT BY: DOCTOR WHO
DATE POSTED: SAT MAR  4 12:28:38 PM

  TO CRACK DUNGEON & THESEUS AND THE MINO TAUR BY TSR, I HAVE A METHOD THAT
REQUI RES NO WIERD HARDWARE OR EXTRA CARDS.  THIS PROGRAM IS WRITTEN IN BASIC
AND US ES FILE NAMES TO LOAD FILES, BUT IT DOE SN'T HAVE A CATALOG SO YOU HAVE
TO CRAC K IT ANOTHER WAY BESIDES DEMUFFIN.HERE IS WHAT TO DO:

BOOT DUNGEON
WHEN IT SAYS"PLEASE WAIT" THEN PRESS RE
SET TWICE.
CALL-151
A44D:4C 69 FF
36:BD 9E 81 9E
MAXFILES1
CLOSE
LOAD HELLO
D6:0
  NOW YOU CAN GO TO BASIC AND LIST THE PROGRAM.BUT THERES MORE PROGRAMS TO THE
GAME!  SO WHAT YOU HAVE TO DO IS FIND TH E ENDING APPLESOFT ADDRESS AT $AF.B0
(L ISTED IN REVERSE ORDER) AND USE THE MON ITOR MOVE COMMAND TO MOVE IT INTO A
SAF E AREA.I CAN'T REMEBER THE ACTUAL ADDRE SS FOR THE PROGRAMS, BUT I WILL
GIVE YO U THE CORRECT FORMAT FOR DOING THIS:  6000<800.[WHAT EVER IS IN
$AB.F0,INREVE RSE ORDER]M [RETURN] THEN YOU BOOT DOS 3.3 AND MOVE IT BACK TO
THE CORRECT PLACE IN MEMORY:  800<6000.[6000+WHATEVER WAS IN AB.F0]M

  NOW FIX THE AB.FO TO WHAT THEY WERE BEF ORE AND SAVE THE PROGRAM!  IN AWHILE,
YOU WILL HAVE IT CRACKED!

BY THE WAY
D6:0 - CANCELS THE THING THAT MAKES THE
       PROGRAM IN MEMORY RUN EVERY TIME
       YOU TYPE A COMMAND IN APPLESOFT.

A44D:4C 69 FF - MAKES IT SO WHEN YOU LO
		AD AN APPLESOFT PROGRAM
		IT PUTS YOU IN THE MONI
		TOR.
36:BD 9E 81 9E RECONNECTS DOS

------------=> DOCTOR WHO <=-----------
