			    THE BYTE'S MAC-CRACK #1

  CHAPTER 1 -- PROTECTION METHODS
  ===============================

  IN THESE EARLY DAYS OF MAC-CRACKING, THERE ARE ONLY A FEW MAIN METHODS OF
PROTECTING PROGRAMS.  ONE OF THE MOST POPULAR METHODS OF PROTECTING A DISK
INCLUDES HIDING AN INVISIBLE FILE ON THE DISK.	THE APPLICATION THEN CHECKS TO
MAKE SURE THAT THE FILE IS ON THE DISK, AND IF IT DOESN'T FIND THE FILE IT WILL
CRASH, HANG, OR TELL YOU TO "INSERT MASTER".  [MULTIPLAN USES THIS METHOD].  AN
INVISIBLE FILE CANNOT BE COPIED WITH THE FINDER, BUT IT WILL BE COPIED WHEN A
FULL DISK COPIER IS USED (IE.  DISKCOPY, DISKUTIL, OR BLOCKSMITH).  TO STOP
PEOPLE FROM COPYING THE WHOLE DISK, THE DISKPROTECT BYTE ON BLOCK #2 IS SET TO
$40.  DISKCOPY (THE COPY PROG WHICH EVERYONE GETS ON THEIR SYSTEM DISK) CHECKS
THAT BYTE, AND IF IT IS A $40, DISKCOPY WILL SPIT OUT THE DISK AND SAY "THAT
DISK IS COPY-PROTECTED!" (SHAME ON YOU).

  NOT ONLY DOES EACH DISK HAVE A PROTECTION BYTE, BUT EACH FILE IN THE DIRECTORY
ALSO HAS ONE.  THIS BYTE (CALLED THE "ATTRIBUTE" BYTE BY EXAMINEFILE) IS TRICKY.
ONCE IT HAS BEEN SET (BY EXAMINEFILE FOR EXAMPLE), THE ONLY WAY TO RESET IT
(RIGHT NOW) IS TO USE A BLOCK EDITOR (SOMETIMES CALLED A 'DISK ZAP').  YOU CAN
USE EXAMINEFILE TO SEE IF A FILE IS PROTECTED THIS WAY (THE ATTRIBUTE BYTE WILL
BE A $40) OR YOU CAN JUST TRY TO MOVE, TRASH, OR DUPLICATE THE SUSPECT FILE.  IF
YOU GET THE MESSAGE:  "THAT MAY NOT BE DUPLICATED OR MOVED" THEN YOU KNOW IT'S
PROTECTED BY THAT BYTE.

  ALL OF THE ABOVE METHODS OF PROTECTION ARE NO CONTEST FOR DISKUTIL AND TWO
DRIVES, BUT IT'S NICE TO BE ABLE TO COPY WITH ONE DRIVE AND TO PUT STUFF ON THE
SAME DISK....

  UNFORTUNATELY, A FEW PROGRAMS [MILLIONAIRE, THINKTANK] ARE NOW USING SOME
STRANGE TRACKS THAT WILL NOT COPY WITH DISKUTIL.  I HAVE BEEN TOLD THAT THE
BLOCKSMITH TYPE OF COPIER WILL CHURN THROUGH THAT TYPE, BUT I HAVEN'T BEEN ABLE
TO GET MY HANDS ON AN ORIGINAL TO TRY IT.

		       THE BYTE

=======================================
    THE BYTE'S MAC-CRACK #2
=======================================

CHAPTER 2 -- CRACKING METHODS
=============================

   REQUIRED TOOLS:
    -BLOCK EDITOR V1.01
    -SETFILE
    -EXAMINEFILE
    -DISKUTIL
    -BLOCKSMITH OR EQUIVALENT
    -BLANK DISKS

  FIRST, I'LL EXPLAIN WHAT WE ARE TRYING TO DO, THEN I'LL GIVE SPECIFICS.  OUR
MAIN OBJECTIVE IS TO MAKE A PROTECTED DISK COPYABLE WITH THE FINDER, BUT MAKING
A DISK COPYABLE WITH DISKCOPY WILL ALSO BE SUFFICIENT (THE EQUIVALENT OF THE
"COPYA" TO THOSE OF YOU IN APPLE //-LAND).  IF DISKCOPY SAYS THAT A DISK IS
COPY-PROTECTED, WE MUST DISABLE THE DISKPROTECT BYTE ON BLOCK #2.  IF THE FINDER
SAYS THAT ANY FILES ON THE DISK CANNOT BE MOVED/DUPLICATED, WE MUST RESET THE
ATTRIBUTE BYTE IN THE DIRECTORY FOR EACH FILE.	IF DISKUTIL OR BLOCKSMITH CANNOT
COPY THE ORIGINAL, THEN YOU WILL HAVE TO MAKE ANY INVISIBLE FILES VISIBLE (WITH
SETFILE) AND MOVE ALL THE FILES TO ANOTHER DISK.  HOPEFULLY THE FILES WILL NOT
BE LOCATION-DEPENDANT.

  OK, LET'S CRACK THE BASIC GENERIC PROTECTION OF MOST PROGRAMS.  FIRST COPY THE
ORIGINAL WITH DISKUTIL OR WHATEVER, THEN USE SETFILE TO MAKE ALL INVISIBLE FILES
VISIBLE (THIS IS OPTIONAL IF YOU WILL END UP WITH A "DISKCOPY", OR "COPYA",
CRACK).  NOW USE THE BLOCK EDITOR TO READ IN BLOCK #2, AND LOOK AT BYTE $0A (10
DECIMAL).  THIS BYTE WILL MOST PROBABLY BE A $40, BUT WHATEVER IT IS, CHANGE IT
TO A $00.  NOW THE DISK CAN BE COPIED WITH DISKCOPY.  NEXT READ IN BLOCK #4,
WHICH SHOULD BE THE FIRST BLOCK OF THE DIRECTORY.  A SHORT DESCRIPTION OF THE
FORMAT OF EACH FILE ENTRY IS IN ORDER.	(NOTE THAT THE LENGTH OF EACH ENTRY
DEPENDS ON THE LENGTH OF THE FILE NAME, WHICH IS LAST).  THE ZEROETH BYTE OF
EACH ENTRY IS THE ATTRIBUTE BYTE WITH THE HIGH BIT SET.  THE NEXT BYTE IS THE
VERSON # (I THINK) AND IS USUALLY ZERO.  THE NEXT FOUR WORDS (1 WORD = 2 BYTES)
ARE THE FILE TYPE & CREATOR; THEY CAN BE CHANGED WITH SETFILE, BUT IT SHOULDN'T
BE NECESSARY.

  NEXT COMES 20 WORDS (40 BYTES) OF DIFFERENT INFO ON THE FILE, NONE OF IT VERY
IMPORTANT.  THE NEXT BYTE IS THE LENGTH OF THE FILENAME AND THEN THE FILENAME IN
POSITIVE ASCII.  IMMEDIATELY FOLLOWING THE NAME (OR ON THE NEXT EVEN BYTE) IS
THE ZEROETH BYTE OF THE NEXT ENTRY...

  SINCE THE ATTRIBUTE BYTE (AS DISPLAYED BY EXAMINEFILE) IS NORMALLY A ZERO, THE
NORMAL VALUE OF THIS ZEROETH BYTE IS $80 (ZERO WITH THE HIGH BIT SET).

  FOR A PROTECTED FILE, THIS BYTE WILL BE A $C0.  CHANGE IT TO AN $80.	THIS
FILE CAN NOW BE MOVED/DUPLICATED.  THE TRICK TO THIS IS FINDING THE ATTRIBUTE
BYTE FOR THE PROTECTED FILES.  THE EASIEST WAY IS TO LOOK FOR FILENAMES IN THE
ASCII DUMP ON THE RIGHT OF THE SCREEN (YOU ARE USING BLOCK EDITOR AREN'T YOU),
AND THEN LOOK AT THE BYTE IMMEDIATELY AFTER THE NAME.  IF IT'S A $C0, THEN THE
ODDS ARE GOOD THAT IT SHOULD BE AN $80.

  YOU WILL GET USED TO FINDING WHAT YOU ARE LOOKING FOR....

  ONCE YOU HAVE DE-PROTECTED THE DISK AND ITS FILES, THE DISK SHOULD BE COPYABLE
WITH DISKCOPY.	HOPEFULLY, IT WILL ALSO WORK IF YOU COPY THE FILES ALONE (ALL
FILES MUST BE VISIBLE), BUT NOT NECESSARILY.  TAKE PFS FOR EXAMPLE:  THERE ARE
TWO PROTECTED FILES ("PFS FIL E" & "PFS REPORT") AND TWO INVISIBLE FILES ("TRACK
2.TEXT" & "TRACK 3.TEXT") .  PFS WORKS FINE WITH THE "TRACK" FILES VISIBLE AND
THE OTHER TWO UNPROTECTED, BUT IF YOU TRY TO COPY THE FILES WITH THE FINDER, THE
FILES WILL NOT END UP IN THE SAME PLACE ON THE DISK, SO PFS WON'T RUN ON THE
FINDER COPY.  (SO PFS IS A "COPYA" OR "DISKCOPY" JOB).  OTHER PROBLEMS YOU MIGHT
ENCOUNTER ARE MODIFIED FINDER & SYSTEM FILES.  MACSLOTS REQUIRES ITS OWN SPECIAL
SYSTEM FILE, SO YOU CAN'T PUT ANY SYSTEM-FILE-USING PROGRAMS ON WITH IT.  (YOU
CAN PUT SOMETHING LIKE ALICE ON WITH IT THOUGH).  IF ANY NEW ADVANCES IN
MAC-CRACKING EMERGE, I'LL CONTINE THE SAGA....


		  HAPPY MAC-CRACKING --
 THE BYTE
Fort Chappa 203-633-2616
