9

---------------------------------------
[Safehouse: 612/724-7066 - Space Quits]


FUN WITH ALARMS
BY THE STAINLESS STEEL RAT

A FACT I FORGOT TO MENTION IN MY
PREVIOUS ALARM ARTICLES IS THAT ONE
CAN ALSO USE POLYURETHANE FOAM IN A
CAN TO SILENCE HORNS AND BELLS.  YOU
CAN PURCHASE THIS AT ANY HARDWARE
STORE AS INSULATION.  IT IS EASIER TO
HANDLE AND DRIES FASTER.

MANY PEOPLE THAT TRAVEL CARRY A POCKET
ALARM WITH THEM.  THIS ALARM IS A SMALL
DEVICE THAT IS HUNG AROUND THE DOOR
KNOB, AND WHEN SOMEONE TOUCHES THE KNOB
HIS BODY CAPACITANCE SETS OFF THE
ALARM.  THESE NASTY NUISENCES CAN BE
FOUND BY WALKING DOWN THE HALLS OF
A HOTEL AND TOUCHING ALL THE DOOR
KNOBS VERY QUICKLY.  IF YOU HAPPEN TO
CHANCE UPON ONE, ATTACH A 3' LENGTH OF
WIRE OR OTHER METAL OBJECT TO THE
KNOB.  THIS WILL CAUSE THE SLEEPING
BUSINESS PIG INSIDE TO THINK SOMEONE
IS BREAKING IN AND CALL ROOM SERVICE
FOR HELP.  ALL SORTS OF FUN AND GAMES
WILL ENSUE.

SOME HIGH-SECURITY INSTALATIONS USE
KEYPADS JUST LIKE TOUCH-TONE PADS
(A REGISTERED TRADE MARK OF BELL
SYSTEMS) TO OPEN LOCKS OR DISARM
ALARMS.  MOST USE THREE OR FOUR DIGITS.
TO FIGURE OUT THE CODE, WIPE THE KEY-
PAD FREE FROM ALL FINGERPRINTS.  AFTER
IT HAD BEEN USED JUST APPLY FINGER
PRINT DUST AND ALL FOUR DIGITS WILL BE
MARKED.  NOW ALL YOU HAVE TO DO IS
FIGURE OUT THE ORDER.

IF YOU WANT TO HAVE SOME FUN WITH A
KEYPAD, TRY PRESSING THE * AND # AT
THE SAME TIME.  MANY UNITS USE THIS AS
A PANIC BUTTON.  THIS WILL BRING THE
OWNER AND THE COPS RUNNING AND EVER-
ONE WILL HAVE A GOOD TIME.  NEVER TRY
TO REMOVE THEM FROM THE WALL, AS THEY
ALL HAVE TAMPER SWITCHES.

ON THE SUBJECT OF HOLDUPS, MOST PLACES
(INCLUDING SUPER-MARKETS, LIQUER
STORES, ETC.) HAVE WHAT IS KNOWN AS A
MONEY CLIP.  THESE LITTLE NASTIES ARE
PLACED AT THE BOTTOM OF A MONEY DRAWER
AND WHEN THE LAST FEW BILLS ARE WITH-
DRAWN A SWITCH CLOSES AND SETS THE
ALARM OFF.  THAT'S WHY WHEN YOU MAKE
YOUR WITHDRAWL IT'S BEST TO HELP YOUR-
SELF SO YOU CAN CHECK FOR THESE LITTLE
NASTIES.  IF YOU FIND THEM, MERELY
INSERT ONES UNDERNEATH THE PILE OF
TWENTIES, AND THEN PULL OUT THE TWEN-
TIES, LEAVING THE ONE-DOLLAR BILL
BEHIND TO PREVENT THE CIRCUIT FROM
CLOSING.

IF YOU SHOPLIFT AND SEE CAMERAS, LOOK
AT THE BRAND.  IF IT IS SURVEILLANCE
VIDEO SYSTEMS (SVS) YOU NEED NOT WORRY.
THESE CAMERAS LOOK REALISTIC TO THE
POINT OF PILOT LIGHTS, COAX, AND
SCANNING.  HOWEVER, THEY ARE ONLY
EMPTY BOXES.
