/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
!				      !
!	  CULTIVATING YOUR OWN	      !
!		MARIJUANA:	      !
!	     A HOW TO GUIDE	      !
!				      !
!	     UPLOADED BY:	      !
!				      !
!	      ________\/	      !
!	     / DE BUG OO	      !
!	     \_\_\_\_\_>	      !
!	     / \ / \ / \	      !
!				      !
/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/

  THE CULTIVATION OF CANNABIS, WHEN DONE PROPERLY, IS AN ENTERTAINING AND
REWARDING HOBBY.  FOR CITY FOLK, HOWEVER, OUTDOOR HORTICULTURE IS DANGEROUS AND
NEARLY IMPOSSIBLE, ESPECIALLY IN NEW YORK STATE.

  THERE ARE THREE SCALES OF PRODUCTION THAT CAN BE ATTEMPTED:

  * SMALL SCALE:  ONE, TWO, OR THREE PLANTS GROWING AT A TIME WILL PROVIDE THE
STEADY POT SMOKER WITH AN OCCASIONAL OUNCE.

  * MEDIUM SCALE:  EIGHT TO 15 PLANTS AT A TIME WILL PROVIDE SUFFICIENT POT SO
THAT PURCHASING IT IS NO LONGER NECESSARY.

  * LARGE SCALE:  UPWARDS OF 20 PLANTS WILL PROVIDE THE AVERAGE FARMER WITH
ENOUGH PRODUCE TO GO COMMERCIAL.  HOWEVER, ANYONE CONSIDERING THIS OUT THE
CAREFULLY BALANCE THE PROFITS AGAINST THE RISKS.


SECURITY
========

  THE MOST IMPORTANT CONSIDERATION IN ANY SCALE OF PRODUCTION IS KEEPING YOUR
PLANTS HIDDEN FAILURE CAN RESULT IN A FREEDOM SHORTAGE!

  ANYONE SERIOUS ABOUT GROWING HIS OWN SHOULD KEEP IN MIND THAT THE LARGER THE
SCALE OF PRODUCTION, THE GREATHER THE IMPRESSION WILL BE ON ANYONE WHO ABSERVES
THE OPERATION, AND THE MORE LIKELY THE WORD WILL SPREAD.

  EVERYONE MUST USE HIS OWN JUDGEMENT ON WHO WILL BE PRIVILEGED TO KNOW OF HIS
AGRICULTURAL ACTIVITIES.  THE PRECAUTIONS MUST BE TAKE TO MAKE SURE THAT NO ONE
ELSE STUMBLES UPON HIS POT FIELD.  WHEN THE PLANTS BECOME LARGE, THERE IS A
TEMPTATION AMONG MOST GROWERS TO PRIDEFULLY SHOW OFF THEIR PLANTS, OFTEN TO THE
WRONG PEOPLE.

  ANOTHER THING TO CONSIDER IS THAT EVERY GROWER WILL ALWAYS BE A BIT PARANOID.
WHEN HE LIES IN BED AT NIGHT HE IS LIKELY TRO THINK THAT WHEN THERE IS AN
UNFRIENDLY KNOCK AT THE DOOR, THERE IS NO WAY TO FLUSH A SIX-FOOT PLANT DOWN
THE JOHN.  ANYONE PREPARED TO GO INTO CULTIVATING MARIJUANA OUT TO REMEMBER --
IF YOU GROW IT, YOU POSSESS IT, AND IT DOES NOT TAKE MUCH FRESH, LIVE POT TO
WEIGH OUT TO A SERIOUS CRIME.


GETTING STARTED
===============

  THE FIRST CONSIDERATION IS ALWAYS THE SEEDS.	ASSUMING THE PLANTS ARE GROWN
WITH CARE AND DILIGENCE, THE SEED STOCK IS THE MOST IMPORTANT IN DETERMINING
THE QUALITY OF THE FINISHED PRODUCT.  GOOD PARENTS WILL YIELD GOOD CHILDREN.
CONTRARY TO POPULAR BELIEF, THE QUALITY OF FINE EASTERN STRAINS CAN BE
APPROACHED INDOORS, PROVIDED ONE STARTS WITH FINE EASTERN SEEDS.

  TO SPROUT SEEDS, THEY SHOULD BE PLACED BETWEEN TWO FOLDED SHEETS OF MOISTENED
TISSUE PAPER AND PLACED IN A CONTAINER IN A DARK PLACE.  USE AT LEAST 20 TIMES
AS MANY SEEDS AS THE NUMBER OF PLANTS DESIRED AT HARVEST.  MANY SEED STOCKS
HAVE A GERMINATION RATE OF LESS THAN 10 PERCENT.  BE SURE TO CHECK SEEDS EVERY
DAY FOR ADEQUATE MOISTURE AND GERMINATION.  THIS IS THE FIRST STEP IN
DEVELOPING THE MOST IMPORTANT INGREDIENT IN SUCCESSFUL POT GROWING --
DILIGENCE.

  BETWEEN FIVE AND SEVEN DAYS AFTER THE SEEDS ARE STARTED, THEY ARE READY TO BE
PLANTED IN CUPS.  EIGHT-OUNCE DIXIE CUPS ARE THE RIGHT SIZE AND ARE
INEXPENSIVE.  THEY SHOULD BE FILLED WITH NEUTRAL POTTING SOIL AND A ONE-QUARTER
TO ONE-HALF INCH SLIT CUT INTO THE BOTTOM OF EACH ONE.	THIS SLIT IS VERY
IMPORTANT, AS THE PLANTS ARE LIKELY TO DIE WITHOUT IT, AND SHOULD BE BIG ENOUGH
TO PASS A STEADY DRIPPING OF WATER.

  SEEDLINGS ARE VERY DELICATE AND SHOULD BE HANDLED BETWEEN THE FUZZY ENDS OF A
PAIR OF PAPER MATCHES, TO AVIOD DAMAGING THEM.	PLANT ONE OR TWO SEEDLINGS IN
EACH CUP, ABOUT THREE-EIGHTS OF AN INCH DEEP, NEAR THE CENTER OF THE CUP.  IF
TWO ARE PLANTED, KEEP THEM ABOUT THREE-QUARTERS OF AN INCH APART.  THE IDEA
BEHIND TWO PLANTS PER CUP IS THAT IF ONE DIES, THERE WILL BE A SPARE.
LIKEWISE, HAVE ABOUT TWICE THE NUMBER OF CUPS AS THE DESIRED NUMBER OF MATURE
PLANTS, SO THAT THE BEST CAN BE SELECTED TO MATURE.  WATER THE CUPS AS SOON AS
THEY ARE PLANTED.


EARLY GROWTH
============

  EVEN UNDER IDEAL CONDITIONS, THE PLANTS WILL GROW PAINFULLY SLOWLY AT FIRST.
MANY WILL NOT SUPPORT THEIR OWN WEIGHT AND FALL OVER.  THIS IS NOT SERIOUS, AND
WILL CORRECT ITSELF LATER ON.  THE FIRST STRUCTURES TO APPEAR ABOVE GROUND ARE
TO OVAL-SHAPED "LEAVES" CALLED COTYLEDONS.  THESE CONTAIN THE NUTRIENTS THE
PLANTS NEED TO GET STARTED.

  AFTER A FEW DAYS, THE FIRST TRUE LEAVES WILL DEVELOP BETWEEN THE COTYLEDONS.
THESE LEAVES WILL APPEAR WRINKLED AND HAVE SERRATED EDGES AS WILL ALL
SUBSEQUENT LEAVES.  THE FIRST TRUE LEAVES (THE FIRST NODE) WILL SEPERATE AND
GROW UP AWAY FROM THE COTYLEDONS.  THE SECOND NODE WILL DEVELOP BETWEEN THE
FIRST LEAVES.  THESE SHOULD HAVE THREE MEMBERS EACH, BUT DON'T FREAK OUT IF
THEY DON'T.  MINOR ABNORMALITIES ARE COMMON AND NOT SERIOUS.  EACH SUCCESSIVE
NODE WILL GROW FROM THE CENTER OF THE LAST.  AFTER A FEW NODES, FIVE- AND THEN
SEVEN-MEMBERED LEAVES WILL DEVELOP.  IF A NODE IS CUT OFF, TWO BRANCHES WILL
GROW HYDRA-LIKE FROM THAT POINT.  LIKEWISE, IF A DEVELOPING NODE IS CUT OFF OF
ANY BRANCH, TWO BRANCHES WILL GROW FROM THAT POINT.  THIS TECHNIQUE OF PRUNING
IS USEFUL FOR CONTROLLING PLANT GROWTH AND ASSURING THAT THEY WILL GROW BIG AND
BUSHY.	ALL GROWERS SHOULD OBSERVE THEIR PLANTS DAILY.	KEEP IN TUNE WITH YOUR
PLANTS!


TRANSPLANTING
=============

  AFTER THE PLANTS IN THE CUPS REACH THEIR FIFTH NODE, THEY ARE READY TO BE
TRANSPLANETED TO A LARGER POT IMPORTANT, IT MUST HAVE A HOLE OR HOLES IN THE
BOTTOM FOR DRAINAGE.  IF THE PLANTS HAVE INADEQUATE DRAINAGE, THEY ARE LIKELY
TO DIE.  ALSO IMPORTANT IS THE CONTAINER SIZE.	FOR INDIVIDUAL PLANTS, A CLAY
FLOWERPOT AT LEAST TEN INCHES WIDE AND ONE FOOT DEEP IS GOOD.  A BETTER
ARRANGEMENT, THOUGH, IS TO GROW A NUMBER OF PLANTS IN ONE LARGE CONTAINER, SUCH
AS A PLANTING BOX AT LEAST ONE FOOT WIDE AND AT LEAST EIGHT INCHES IN LENGTH
FOR EACH PLANT.

  FILL THE CONTAINER WITH STANDARD OUTDOOR POTTING SOIL.  YOU WILL NEED 10 TO
20 POUNDS OF SOIL PER PLANT DEPENDING UPON HOW CLOSE THE PLANTS ARE TO BE
SPACED.  A ONE-FOOT WIDE BOX CAN TAKE ONE ROW OF PLANTS 10 TO 12 INCHES APART,
OR TWO DIAGONAL ROWS, ABOUT SIX TO SEVEN INCHES APART.	THE FORMER ARRANGEMENT
WILL GROW BIGGER PLANTS, WHILE THE LATTER WILL GROW MORE PLANTS.

  SELECT THE BEST PLANTS FOR TRANSPLANTING.  WATER THE CUPS ABOUT AN HOUR
BEFORE TRANSPLANTING.  DIG A HOLE ABOUT FOUR INCHES WIDE AND ABOUT SIX INCHES
DEEP WHERE THE PLANT IS TO GO.	WITH A SHARP MATTE KNIFE OR RAZOR BLADE,
CAREFULLY CUT THE CUP SO THAT IT CAN BE PEELED AWAY.  THEN, WITHOUT BREAKING
AWAY THE DIRT WHICH SURROUNDS THE ROOTS, PEEL THE CUP AWAY SO THAT NO PAPER
REMAINS.  SUPPORTING THE DIRT FROM THE BOTTOM WITH A SPOON, LOWER IT INTO THE
HOLE.  BURY THE PLANT ABOUT ONE-HALF INCH DEEPER THAN IT WAS IN THE CUP.
REPEAT THE PROCEDURE FOR EACH PLANT.

  WHEN ALL THE DESIRED PLANTS ARE IN THE BOX, WATER THOROUGHLY.  THE PLANTS
THAT DO NOT MAKE IT TO THE LARGE CONTAINER SHOULD BE SAVE AND CARED FOR THE THE
CUPS.  THEY WILL CONTINUE TO GROW TO A HEIGHT OF TWO FEET, AND CAN PROVIDE
INTERIM POT FOR THE MOMENT.  THEY CAN ALSO PROVIDE SPARE PLANTS IN CASE ANY IN
THE BOX SHOULD FAIL.  FOLLOWING TRANSPLANTING, THE PLANTS MAY GO THROUGH A
SHORT TRAUMA LASTING A FEW DAYS.  THE BEST PART OF TRANSPLANTING FOR BOTH
PLANTS AND FARMER IS THAT IT ONLY NEED BE DONE ONCE.

NUTRITION
=========

  THE MATERIAL NEEDS OF CANNABIS SATIVA ARE SIMPLE:  AIR, WATER AND A BIT OF
FERTILIZER.  EVEN IN THE 1980'S AIR REMAINS AN ABUNDANT COMMODITY, AND AN
ADEQUATE SUPPLY CAN BE FOUND IN MOST RESIDENCES.  BE SURE THAT THE AIR IS ABOVE
FREEZING, BELOW 120 DEGREES FAHRENHEIT, AND FREE FROM CIGARETTE, POT OR ANY
OTHER KIND OF SMOKE.

  WATER AND FERTILIZER CAN BE TAKEN CARE OF IN ONE STEP.  USE ONE TABLESPOON OF
WATER-SOLUBLE COMMERCIAL FERTILIZER IN A GALLON OF WATER.  THIS IS A STOCK
SOLUTION.  TO OBTAIN A WATERING SOLUTION, DILUTE STOCK FIVE TO ONE.  PLANTS IN
CUPS SHOULD BE WATERED DAILY WITH THIS SOLUTION.  THE HOLE IN THE BOTTOMS OF
THE CUPS WILL PREVENT OVER-WATERING, SO BE LIBERAL.  MAKE A GOOD PUDDLE IN EACH
CUP.

  LATER, WHEN THE PLANTS ARE IN THEIR FINAL FLOWERPOT OR PLANTER, WATERING CAN
BE CUT TO TWO OR THREE TIMES A WEEK.  WATER ENOUGH SO THE THE TOPSOIL IS NEVER
DRIED OUT.  AGAIN, IT PAYS TO BE LIBERAL; AS THE PLANTS GET BIGGER, THEY WILL
NEED MORE WATER.  THIS RISE IN CONSUMPTION SURPRISES MANY GROWERS.  IT CAN
EASILY REACH A GALLON A WEEK FOR EACH PLANT -- JUST KEEP GIVING THEM WHAT THEY
NEED.

LIGHT
=====

  ALL GREEN PLANTS NEED LIGHT TO GIVE THEM THE ENERGY TO TURN AIR, WATER, AND
FERTALIZER INTO FOOD.  POT PLANTS GROW BEST IN MAXIMUM LIGHT.  AS SOON AS THEY
ARE IN THE CUPS, THEY SHOULD BE STARTED ON A DIET OF LIGHT AT LEAST TWELVE
HOURS PER DAY.	A LARGE WINDOW, PREFERABLY FACING SOUTH, IS A GOOD LIGHT
SOURCE, BUT THERE ARE A COUPLE OF DRAWBACKS.

  FIRST IS THE LOCAL WEATHER, WHICH DOES NOT GUARANTEE OPTIMUM LIGHT.  THE
SECOND MORE OBVIOUS PROBLEM IS THAT THE CROP CAN BE SEEN FROM THE OUTSIDE.
THIS CAN BE OVERCOME BY PLACING A SHEET OF POLYETHYLENE PLASTIC (LIKE
DRYCLEANER BAGS) OVER THE GLASS.  THIS WILL LET LIGHT IN, BUT NOT CURIOUS EYES.

  FOR SMALL-SCALE PRODUCTION, A WINDOW IS SATISFACTORY, BUT FOR ANYTHING MORE
THAN A FEW PLANTS, ARTIFICIAL LIGHT PROVIDES BETTER GROWTH.  ALTHOUGHT
INCANDESCENT BULBS WORK, FLOURESCENT LIGHTS PROVIDE BETTER RESULTS AND USE
ABOUT ONE-THIRD THE ELECTRICITY.  IF YOU PAY FOR YOUR OWN UTILITIES, THAT'S
IMPORTANT.  FOUR-FOOT SHOPLIGHT FIXTURES, CONTAINING TWO 40-WATT TUBES ARE
AVAILABLE AT MOST DEPARTMENT STORES WHICH SELL HARDWARE AND ARE FREQUENTLY
SALE-PRICED AT $15 TO $20.  THESE PROVIDE SATISFACTORY RESULTS ON AS MANY AS
EIGHT PLANTS, AND EXCELLENT RESULTS ON FOUR PLANTS.  USE AS MUCH LIGHT AS YOU
CAN AFFORD; THE MORE LIGHT THE BETTER.	PLANTS COMPETE VIGOROUSLY FOR LIGHT
ONCE THEY ARE IN THE BOX.  IT IS UP TO THE GROWER TO MODERATE THE COMPETITION
BY SELECTIVE PRUNING, AND CAREFUL POSITIONING OF LIGHT SOURCES.  WITH A LITTLE
INGENUITY AND SOME CHAIN OR ROPE, IT'S POSSIBLE TO RIG A SUSPENSION FOR
FLUORESCENT FIXTURES THAT CAN BE EASILY ADJUSTED TO ANY NUMBER OF POSITIONS.
THE ALL-IMPORTANT ADJUSTMENT IS HEIGHT.  LAMPS SHOULD BE RAISED TO AVOID HAVING
PLANTS GROW INTO THEM.	BRANCHES LEFT IN FIXTURES WILL DIE.  PRUNING IS ALSO
ADVISED TO PREVENT PLANTS FROM GROWING TO THE CEILING, SINCE THE LIGHTS CANNOT
EASILY BE RAISED BEYOND THAT POINT.  (YES, PLANTS WILL GROW THAT HIGH IF YOU
LET THEM.) FOIL REFLECTORS CAN ALSO BE USED TO FURTHER MAXIMZE LIGHT FALLING ON
THE PLANTS.  SIXTEEN HOURS PER DAY IS THE IDEAL PHOTO PERIOD FOR POT.  A
24-HOUR TIMER CAN TAKE CARE OF THIS AUTOMATICALLY, OR A CONSCIENTIOUS GROWER
CAN TURN THE LIGHTS ON WHEN HE GETS UP AND OFF WHEN HE GOES TO BED.  THE LATTER
METHOD IS RECOMMENDED, AS IT WILL KEEP THE GROWER IN CLOSER TOUCH WITH HIS
PLANTS.


CARING FOR MATURE PLANTS
========================

  A FEW WEEKS AFTER THE PLANTS GO INTO THE BOX, THEIR GROWTH WILL ACCELERATE
TRIM THE SIXTH NODE AS SOON AS IT HAS BECOME BIG ENOUGH TO DO SO.  THE CLIP
EVERY THIRD OR FOURTH NODE TO PROMOTE BRANCHING AND BUSHYNESS.

  WHEN THE PLANTS REACH A HEIGHT OF FOUR FEET, THEY CAN BE PUT ON A STEADY
STATE ONCE A WEEK THEY SHOULD BE CUT BACK TO FOUR FEET.  THE STEADY STATE CAN
BE MAINTAINED INDEFINITELY, WITH EACH WEEK'S CUTTINGS PROVIDING A WEEK'S
SMOKING.  EIGHT PLANTS WILL PROVIDE THREE PEOPLE WITH ENOUGH POT TO GET HIGH
ABOUT ONCE A DAY, BUT THE PLANTS CAN NEVER REACH THIER FULL STRENGHT POTENTIAL
IN THE STEADY STATE.

  WHEN PRUNING, REMEMBER, EACH EXISTING LEAF CAN SPROUT ONLY ONE BRANCH.  MAKE
SURE THE CUT IS MADE IMMEDIATELY ABOVE A LEAF THAT CAN STILL GENERATE A BRANCH.

  ANYTIME AFTER THE MIDDLE OF THE FOURTH MONTH AFTER GERMINATION, THE PLANTS
CAN BE ALLOWED TO COMPLETE THEIR LIFE CYCLE.  THE PRUNING SHOULD BE STOPPED OR
GRATLY REDUCED, AND THE PHOTO PERIOD SHOULD BE CUT TO EIGHT TO 12 HOURS PER
DAY.  THIS WILL STIMULATE FLOWERING.  AS THE PLANTS GET TALLER, FLOWERS WILL
BEGIN TO APPEAR WHERE THE LEAVES JOIN THE BRANCHES.  THIS IS THE TIME TO
DISCONTINUE.

  AS WITH ANY OTHER LIVING THING, PLANTS INCLUDING CANNABIS COMES IN BOTH MALE
AND FEMALE.  MALE FLOWERS CONSIST OF TINY YELLOW-GREEN PUFF BALLS (STAMENS)
HANGING FROM MINUTE FILAMENTS.	FEMALE FLOWERS CONSIST OF TOW TINY,
FEATHER-LIKE STRUCTURES (PISTILS) PROTRUDING FROM A SMALL VASE-LIKE STRUCTURE
(BRACT).  PLEASE NOTE, IT IS NOT UNCOMMON TO HAVE BI-SEXUAL PLANTS.  THEY ARE
NOTHING TO GET UPSET ABOUT.

  CONTRARY TO POPULAR BELIEF, MALE PLANTS ARE NOT IMPOTENT.  ACCORDING TO THE
CONNOISSEUR'S HANDBOOK OF MARIJUANA BY W.D.  DRAKE JR., MALES ARE SLIGHTLY LESS
POTENT, BU PERSONAL EXPERIENCE INDICATES A DIFFERENCE IN QUALITY THAT IS HARDLY
NOTICEABLE.  IN FACT, MALE FLOWERS ARE A SMOKING DELICACY.

  IF OFFSPRING ARE DESIRED, BE SURE TO SHAKE SOME MALE PLANTS SO THAT POLLEN
WILL GET TO THE FEMALES.  WITHIN A MONTH OF THE FIRST FLOWERS, SOME OF THE
BRACTS ON THE FEMALES WILL BEGIN TO GROW LARGER.  EACH OF THESE IS NURTURING A
SEED.  REMEMBER, AT THIS POINT, THE FEMALE PLANT WILL DEVOTE ALL OF ITS ENERGY
TOWARD SEED PRODUCTION, TO THE NEGLECT OF RESIN PRODUCTION.

  THE OPTIMUM TIME FOR HARVESTING THE FEMALE PLANT IS WHEN THE FIRST SEEDS ARE
MATURE.  TO CHECK, PULL OFF A POD.  THERE SHOULD BE A SEED INSIDE.  IF MORE
SEEDS ARE DESIRED, SOME SACRIFICES IN POTENCY MUST BE MADE.  MALE PLANTS SHOULD
BE HARVESTED WHEN THEY ARE FULLY FLOWERED.

  FOR THOSE INTERESTED IN CONTINUOUS PRODUCTION A FUTURE CROP SHOULD BE STARTED
BETWEEN WET TISSUES AT ABOUT THE TIME THE FIRST FLOWERS APPEAR ON THE MATURING
PLANTS.  REMEMBER, THE GREATER MAJORITY OF VEGETABLE MATERIAL COMES INTO BEING
BETWEEN THE TIME PLANTS ARE PUT IN THE BOX AND HARVEST TIME.  THERE IS A
TENDENCY FOR MANY GROWERS TO NEGLECT THEIR PLANTS DURING THE LATER STAGES OF
DEVELOPMENT.  CHECK THEM DAILY!  THIS WILL ASSURE THAT THE PLANTS WILL GROW TO
THEIR FULLEST POTENTIAL.

HARVESTING AND PREPARATION
==========================

  WEEK BEFORE HARVEST, WATERING SHOULD BE DISCONTINUED.  TO HARVEST, GENTLY
REMOVE THE PLANTS AND CAREFULLY SHAKE OFF THE LOOSE DIRT AND HANG THE PLANT
UPSIDE DOWN IN A DRY PLACE.  PLANTS CAN BE DRIED IN A WARM OVEN FOR THOSE WHO
CAN'T WAIT, BUT ROOM-TEMPERATURE DRYING WILL YIELD BETTER POT (WITHOUT MAKING
THE ROOM SMELL OF "ROAST POT").  THE LOWER LEAVES (THOSE CLOSEST TO THE CEILING
NOW) WILL DRY FIRST.  THE WHOLE PLANT SHOULD BE DRY IN ABOUT TWO WEEKS.  THE
JUST PULL THE LEAVES OFF AND DO WITH THEM WHATEVER SEEMS APPROPRIATE.

  COOKING WITH GRASS IS LIMITED ONLY BE THE IMAGINATION OF THE CHEF.  LEAVES
SHOULD BE CHOPPED FINELY IN A BLANDER AND THEN SAUTEED IN A BUTTER OR MARGARINE
BEFORE THEY GO INTO ANY RECIPE.  AN OUNCE OF POT CAN ABSORB AS MUCH AS TWO
STICKS OF BUTTER.  THIS IS AN IMPORTANT STEP BECAUSE IT PROVIDES A MEDIUM OF
ABSORPTION FOR THE HUMAN DIGESTIVE SYSTEM.  CARE IS ADVISE ON HOW MUCH YOU EAT;
WHEN YOU ARE TOO HIGH TO MOVE, YOU WILL KNOW WHY.


LITTLE BEASTIES
===============

  THERE ARE FEW PARASITES THAT ATTACK CANNABIS.  SHOULD YOUR PLANTS BECOME
INFESTED WITH INSECT PESTS, DO NOT USE A COMMERCIAL INSECTIDE.	A COMMON
VISITOR TO POT GARDENS IS A SMALL LIGHT-COLORED SPIDER.  THESE SPIDERS ARE
BENEFICIAL AND SHOULD NOT BE KILLED.  ANOTHER BENEFICIAL VISITOR, THAT MUST BE
IMPORTED, IS THE COMMON EARTHWORM.

