		     COLA GUIDE FOR THE 80'S

  THIS IS A COMPLETE GUIDE TO THE MAJOR COLAS ON THE MARKET MIDWAY THROUGH THE
80'S.  WITH ALL OF THE CHANGES THE COCA COLA COMPANY IS MAKING, THE CUTTING
COMERCIALS THAT PEPSI IS MAKING, AND THE COME-BACK RC COLA IS TRYING TO MAKE, A
COOL REFRESHMENT ON A WARM DAY CAN BE VERY CONFUSING.

		   THIS IS ONLY A GUIDE OF THE
	       COLAS, NOT OTHER SOFT-DRINKS, LIKE
		       BIG RED AND SPRITE
       _
  COLA (KO`LE), n.  A CARBONATED SOFT DRINK HAVING A SYRUP BASE MADE FROM THE
DRIED LEAVES OF THE COCA PLANT AND THE SEEDS OF KOLA NUTS, TOGETHER WITH
SWEETENERS AND OTHER FLAVORINGS.

  I WILL START WITH COCA COLA.	THIS COMPANY STARTED WITH A BEVRAGE CALLED COKE,
WITCH IS BELIEVED TO HAVE ONCE CONTAINED COCAINE.  AS THE FIRST 99 YEARS PASSED
(ENDING IN 1985), COKE KEPT ITS ORIGINAL RECIPE, AND PRODUCED OTHER POPULAR SOFT
DRINKS:

COKE-> A SEMI-SWEET DRINK WITH A 'CARBONATION-BITE'.

  AMERICANS, THOUGH, WANTED A SUGAR-FREE DRINK TO KEEP THIER WASTE-LINES TRIM,
THUS COCA COLA WAS FORCED TO PRODUCE ANOTHER DRINK.

  TAB-> A SUGAR-FREE DIET DRINK PRODUCED TO TASE LIKE COKE, BUT WAS FAR-SWEETER.

  DIET COKE-> A COKE WITH A NUTRA-SWEET REPLACEMENT FOR SUGAR THAT IS ALSO
SWEETER THAN COKE.

  CAFFEINE FREE DIET COKE-> A DIET COKE WITHOUT CAFFEINE.

  COME EARLY 1985, THOUGH, COCA COLA DECIDED TO CHANGE ITS ORIGINAL RECIPE, AND
CALL THE DRINK 'NEW COKE'.  BUT AFTER MONTHS OF COMPLAINT, COCA COLA ANNOUNCED
THAT IT WOULD BRING BACK OLD COKE, WITH THESE PRODUCT NAMES:

  COKE CLASSIC-> THE ORIGINAL COKE.

  COKE-> THE NEWER, SWEETER, COKE.

  FINALLY, COKA COLA ALSO DECIDED TO CREARE A NEW COLA THAT IS BASED IN COKE'S
HISTORY.  MANY BAR'S AND TAPS IN THE PAST DECADES HAVE ADDED EITHER CHERRY OR
VANILA FLAVORS TO ADD FLAVOR TO THE ORIGINAL COLA, BRINGING ABOUT:

  CHERRY COKE-> THE ORIGINAL FLAVOR OF COKE WITH A CHERRY FLAVORING, MY PERSONAL
FAVORITE, AFTER DRINKING IT FOR ONLY ONE WEEK.

  'HAVE A COKE AND A SMILE'

  NEXT, I WILL DISCUSS PEPSI COLA.  PEPSI COLA WAS PUT ON THE MARKET SHORTLY
AFTER COCA COLA.  PEPSI HAS, THOUGH HAS CHANGED ITS RECIPE ABOUT FOUR TIMES
WHILE OUT ON THE MARKET.

  PEPSI-> A SOFT-DRINK THAT IS NOT AS CARBONATED AS COKA COLA, YET BASICALLY THE
SAME.

  PEPSI COLA ALSO FACED THE SAME SITUATION COCA COLA DID, AND THEY TO WERE
FORCED TO PRODUCE DIET DRINKS:

  DIET PEPSI-> A SUGAR-FREE SOFT-DRINK (WITH NUTRA-SWEET).  IT IS SWEETER THAN
PEPSI.

  DIET PEPSI FREE-> A SUGAR FREE/CAFFEINE FREE SOFT-DRINK (ALSO WITH
NUTRA-SWEET).  IT TOO IS SWEETER THAN PEPSI.

  PEPSI FREE-> A CAFFEINE FREE SOFT-DRINK THAT IS SWEETER THAN PEPSI.

  'PEPSI, THE TASTE OF A NEW GENARATION'

  NEITHER COKE NOR PEPSI STARTED WITH INTENTIONS OF BEING SOFT-DRINKS.	NO, THEY
WERE INTENDED AS 'WONDER DRUGS' INSTEAD.  THEY WERE SAID TO BE ABLE TO CURE
ANYTHING, BUT THEY WERE CHANGED TO SOFT-DRINKS, WHERE THEY SOON BECAME RIVALS.

  AFTER THESE TWO COMPANIES RULED THE MARKET, A NEW SOFT DRINK CAME OUT WITH A
MUCH SWEETER AND LESS CARBONATED TASTE.  THIS SOFT DRINK TRIED TO GAIN A PLACE
ON THE MARKET WITH ONE MAIN PRODUCT INSTEAD OF FOUR TO FIVE OR THEM.  THIS DRINK
GOES THROUGH PHASES OF POPULARITY.

  ROYAL CROWN COLA-> A SWEET, LESS CARBONATED SOFT DRINK, PROBABLY PUT ON THE
MARKET TO FURTHER CONFUSE US.

  ROYAL CROWN COLA ALSO FACED THE SAME PROBLEM THAT COKE AND PEPSI DID, IT ALSO
WAS FORCED TO PRODUCE A DIET DRINK, BUT THIERS WAS ALSO SODIUM FREE.

  DIET RITE-> A SUGAR FREE, CAFFEINE FREE, AND SODIUM FREE SOFT DRINK.

  'SOME PEOPLE GO OUT OF THIER WAY FOR AN RC'

  I HOPE THAT THIS GUIDE HAS HELPED SLIGHTLY, IF NOT CONFUSED YOU GREATLY.  TAKE
MY ADVICE AND STICK TO THE ORIGINAL, LESS CONFUSING DRINK:

  WATER-> A TASTELESS, CARBONLESS, AND CALORIELESS DRINK CREATED BEFORE THE HOMO
SAPIEN.


	      --THE PHANTOM


---------------------------------------
