---------------------------------------

-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-
!									     !
!		     THE COMICBOOK COLLECTOR'S HANDBOOK                      !
!									     !
!			  WRITTEN BY: PROFESSOR X			     !
!		     MENTAL GUIDANCE: ELECTRIC EYE			     !
!			NO THANKS TO: NIGHT CRAWLER			     !
!		      SPECIAL THANKS: AGENT 007 			     !
!									     !
-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-

===============
!	      !
! DEFINITIONS:!
!	      !
===============

BACK ISSUE: AN ISSUE OF ANY COMIC BOOK PREVIOUS TO THE LATEST ONE. THIS CAN
	    REFER TO LAST MONTH'S ISSUE, OR AN ISSUE PUBLISHED MANY YEARS AGO.

COMICS CODE AUTHORITY: AN ORGANIZATION THAT MOST PUBLISHERS OF COMIC BOOKS
		       MUST SHOW ALL THEIR MATERIAL TO BEFORE PUBLISHING.
		       THE CODE DECIDES WHETHER OR NOT THE COMIC BOOK IS
		       WITHIN THE GUIDELINES SET BY THE CODE TO INSURE IT IS
		       SUITABLE TO BE READ BY YOUNGER READERS.

COMICS CONVENTION: A GATHERING OF FANS, COLLECTORS, PROFESSIONAL COMIC
		   ARTISTS AND WRITERS AND COMIC BOOK DEALERS, TO ENJOY,
		   DISCUSS AND SELL COMICS. CONVENTIONS ARE USUALLY HELD IN
		   HOTELS, AND ALSO FEATURE MOVIES, DISPLAYS, ETC.

GOLDEN AGE: A PERIOD OF TIME IN THE HISTORY OF COMICS RUNNING FROM AROUND
	    1935 (WHEN COMICS BEGAN PUBLISHING) TO 1949. THESE COMICS ARE
	    KNOWN FOR THEIR QUALITY, AND MANY PRE-CODE ISSUES HAVE BECOME
	    COLLECTORS ITEMS.

SILVER AGE: THIS PERIOD BEGAN IN 1956 WITH SHOWCASE #4, WHEN THE FLASH
	    APPEARED, BRINGING IN THE NEW WAVE OF SUPER HEROES. MARVEL HAD
	    THE GREATEST IMPACT ON THE FUTURE OF COMICS WHEN THEY PUBLISHED
	    AMAZING FANTASY #15. THE SILVER AGE RUNS INTO THE LATE 1960'S.

-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-


==================
!		 !
! GRADING COMICS !
!		 !
==================

THE FOLLOWING IS A GUIDELINE FOR THE BEGINNING COLLECTOR. AS YOU BECOME MORE FA

-=COVERLESS=-
THESE ARE THE ONES WITH NO COVERS, AND GENERALLY ARE NOT COLLECTED.

-=POOR=-
UNCOLLECTABLE, INCOMPLETE, BADLY WORN, TORN COVER, WATER DAMAGED, ETC.

-=FAIR=-
COMPLETE COMIC, WITH SOME TEARS IN THE COVER AND/OR ROLLED SPINE, SOILED PAGES.

-=GOOD=-
COMPLETE WITH COVER ATTACHED AND SOME SIGNS OF SOILING AND WEAR IN PARTICULAR.

-=FINE=-
SLIGHT SIGNS OF WEAR, BUT STILL WITH COVER GLOSS - NO TEARS OR OBVIOUS DEFECTS.

-=VERY FINE=-
THE BORDERLINE BETWEEN FINE AND MINT IS THIS ONE. GENERALLY A VERY NICE-LOOKING
-=MINT=-
PERFECT CONDITION, COMPLETE, LIKE NEW, STILL WITH ORIGINAL PRINT LUSTRE.

-=PRISTINE MINT=-
JUST OFF THE PRESS, PERFECT COMIC. FEW ARE PRISTINE MINT BECAUSE OF THE PRINTING

-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-


===========================
!			  !
! GUIDELINES ON 	  !
!     SELLING YOUR COMICS !
!			  !
===========================

THE TIME MAY COME WHEN YOU MAY WANT TO SELL YOUR COMICS. THE FOLLOWING GUIDELIN
E SHOWS YOU HOW...

-=TITLE=-
POPULAR TITLES SUCH AS THE X-MEN OR SPIDER-MAN WILL ALWAYS BRING A HIGHER PRICE

-=CONDITION=-
A BOOK IN GOOD CONDITION WILL NEVER BE WORTH AS ONE IN FINE OR MINT NO MATTER W
HAT KIND IS IT.

-=DEALER/COLLECTOR=-
IT IS IMPORTANT TO UNDERSTAND THE DIFFERENCE BETWEEN SELLING TO A DEALER OR A C
LUB.

-=COROLLARY=-
IT TAKES TIME FOR A COMIC TO BECOME VALUABLE. YOU CAN'T BUY A COMIC TODAY AND E
XPECT IT TO BE VALUABLE TOMORROW.


========================
!		       !
! STORING COMIC BOOKS  !
!		       !
========================

1. STORE COMICS IN BAGS MADE FROM MYLAR.
   -PLASTIC BAGS ARE GOOD ONLY FOR TEMPORARY STORAGE BECAUSE OF THEIR ACIDITY.
   -NEVER USE POLETHYLENE BAGS BECAUSE OF THEIR HIGH ACID CONTENT.
2. PACK COMICS IN BOXES THAT ARE TO THEIR DIMENSIONS.
   -NEVER STACK COMICS.
   -TOO LARGE OF BOXES WILL COST COMICS TO SAG AND THUS BEND.
3. NEVER READ A COMIC MORE THAN ONCE.
   -EACH TIME YOU READ IT, THE MORE IT IS SOILED AND THE LESS VALUABLE IT IS.
   -IT IS RECOMMENDED THAT YOU BUY 2 COPIES; 1 TO READ, THE OTHER TO KEEP.
4. NEVER STORE IN DIRECT LIGHT.
   -SUNLIGHT WILL RUIN COMICS NO MATTER WHAT YOU DO.
5. KEEP UPRIGHT IN A DARK COOL PLACE.

-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-=%><%=-

