 F O N T R I X
BY DATA TRANSFORMS
Arrakis - 612/561-0939

BOOT-UP
=======

FIRST, CONFIGURE YOUR FONTRIX DISK FOR YOUR COMPUTER AND PRINTER.


MAKING A GRAFILE
=================

   WHAT IS A GRAFILE?  A GRAFILE IS A BINARY FILE WHICH HOLDS ALL OF THE
EXTENDED SCREENS THAT YOU WILL BE WRITING ON.  THE GRAFILE MUST BE MADE BEFORE
YOU START WRITING ON THE SCREEN.  ONCE MADE, THE GRAFILE RECORDS INFORMATION
EACH TIME YOU GO OFF THE SCREEN YOU ARE DRAWING ON AND THEN GIVES YOU MORE
ROOM, UNTIL YOU ARE OUT OF IT.

   FIRST, CHOOSE THE "G" COMMAND FROM THE MAIN MENU AND GO TO THE GRAPHIC
WRITER SECTON.	ONCE THERE, YOU SHOULD LOAD YOUR FONT THAT YOU WISH TO USE ON
THE GRAFILE.  IF YOU DON'T KNOW WHAT FONT YOU WANT TO USE, JUST HIT THE "D"
COMMAND AND CATALOG THE DISK.  ONCE YOU'VE FOUND THE FONT YOU WANT TO LOAD,
JUST LOAD IT BY HITTING THE "F" COMMAND AND TYPE IN THE FILE NAME, WITHOUT THE
"SET" PART, IT LOADS THAT AUTOMATICALLY.

   NEXT, YOU NEED TO OPEN THE GRAFILE.	DEPENDING ON THE SIZE YOU WISH TO OPEN
IT AS, YOU WILL NEED, ROOM ON ANOTHER DISK FOR IT.  IT'S A GOOD IDEA TO HAVE 1
DISK COMPLETELY FOR GRAFILES.  ANYWAYS, CHOOSE DTHE "O" COMMAND AND ENTER THE
HORIZONTAL AND VERTICAL SECTORS (A TABLE FOR DIFFERENT SECTORS ARE AT THE END
OF THIS SECTION).  THE DISK WILL WHIR FOR A WHILE AND THEN, THE GRAFILE WILL BE
MADE.

   NEXT, CHOOSE THE "W" COMMAND AND MAKE SURE THE GRAFILE DISK IS IN THE DRIVE.
YOU WILL NOW BE PROMPTED IN FRONT OF A BUNCH OF COMMANDS, THESE ARE THE HELP
COMMANDS, AND CAN BE DISPLAYED AT ANYTIME BY HITTING <CTRL-A>.	NOW YOU CAN
TYPE WHATEVER YOU WANT, AND WHEN YOU ARE READY TO CLOSE THE GRAFILE, JUST TYPE
<CTRL-Q> AND THEN YOU WILL BE BACK AT THE MENU.

   NOW, TYPE "C" FOR CLOSE AND THE GRAFILE WILL BE CLOSED.  YOU CAN NOW GO TO
THE DUMP SECTION AND PRINT OUT YOUR GRAFILE.  IN THAT SECTION ALL YOU HAVE TO
DO IS INPUT THE NAME OF THE GRAFILE AND THEN JUST MAKE SURE YOUR PRINTER IS ON.


HORIZONTAL & VERTICAL SECTORS
=============================

HORIZONTAL SECTORS FOR A RGUALAR 80 COLLUMN PIECE OF PAPER IS 16.
HORIZONTAL SECTORS FOR A LABEL IN PERFORATED HOLDER IS 6.
MINIMUM HORIZONTAL SECTORS IS 5.
MAXIMUM HORIZONTAL SECTORS IS 20.
MINIMUM VERTICAL SECTORS IS 6.
MAXIMUM VERTICAL SECTORS IS 20.


GRAPHIC WRITER COMMAND CONTROL KEYS
===================================

CTRL - A = ASK FOR HELP (DISPLAYS SCREEN)
CTRL - B = SET BACKGROUND COLOR (CTRL-B + #)
CTRL - C = CAPS LOCK & UNLOCK
CTRL - D = DEFAULT WINDOW (RESELECTS WINDOW TO FULL SCREEN)
CTRL - E = ERASE WINDOW
CTRL - F = SET FOREGROUND COLOR (CTRL-F + #)
CTRL - G = GRAPHIC INPUT SELECTS CURRENT GRAPHIC INPUT DEVICE
CTRL - H = BACKSPACE
CTRL - I = INVERSE
CTRL - J = LINEFEED
CTRL - K = REVERSE LINEFEED
CTRL - L = SET LINEFEED SPACING (CTRL-L + #)
CTRL - M = CARRIAGE RETURN
CTRL - N = NORMAL (CANCELS INVERSE)
CTRL - O = OVERLAY (CANCELS R & T)
CTRL - P = POINT MODE (DRAW WITH A SINGLE DOT)
CTRL - Q = QUIT (BACK TO GRAPHIC WRITER MENU)
CTRL - R = REPLACE (CANCELS O & T)
CTRL - S = SET SPACING BETWEEN CHARACTERS (CTRL-S + #)
CTRL - T = TRANSPARANT. INVERT BACKGROUND (CANCELS R & O)
CTRL - U = FORWARD SPACE
CTRL - V = VIEWPORT. VIEW FILE PARAMETERS
CTRL - W = SET WINDOW (USE I,J,K,M TO SET)
CTRL - X = BACKSLASH CHARACTER
CTRL - Y = YANK SCREEN FROM GRAFILE (RESTORE)
CTRL - Z = ZERO CURSOR (MOVE TO TOP LEFT OF SCREEN)
ESC	 = USE I,J,K,M TO MOVE CURSOR.


FONTRIX FONT EDITOR
===================

SET PARAMETERS:

SET NAME - 1 TO 15 CHARACTERS (ALPHANUMERIC AND PERIOD ONLY)
TOTAL CHARACTERS - 1 TO 94
FIRST CHARACTER - "!"-FIRST "-"-LAST
HORIZONTAL CELL SIZE - 1 TO 32
VERTICAL CELL SIZE - 1 TO 32
PROPORTIONAL - YES/NO

EDIT SET COMMAND KEYS:

I,J,K,M, AND ARROWS = MOVE CURSOR TO CHOOSE WHICH CHARACTER TO EDIT
V = VIEW THE ENTIRE SET (AGAIN TO CANCEL)
C = COPY ONE CHARACTER CELL INTO ANOTHER
O = OVERLAY ONE CHARACTER CELL OVER ANOTHER
RETURN = SELECT A CHARACTER FOR EDITING
Q = QUIT AND RETURN TO FONT EDITOR MENU

EDIT SINGLE CHARACTER COMMAND KEYS:

I,J,K,M,AND ARROWS = MOVE CURSOR WITHIN CHARACTER CELL
SPACE-BAR = CHANGE A PIXEL(ON/OFF)
CTRL - E = ERASE CONTENTS OF CHARACTER CELL
CTRL - P = POSITION WITHIN CELL. (I,J,K,M,ARROWS)
CTRL - X = RETURN TO EDIT SET WITHOUT SAVING CHANGES TO CHARACTER
RETURN = RETURN TO EDIT SET AND SAVE CHANGES TO CHARACTER


NOTES ABOUT GRAPHICS
====================

   ONE VERY IMPORTANT ASPECT OF FONTRIX IS THE ABILITY TO PRINT GRAPHICS ALONG
WITH YOUR GRAFILE.  IN OTHER WORDS, YOU WANT TO BE ABLE TO NOT ONLY WRITE WORDS
AND PRINT THEM OUT; YOU WANT TO BE ABLE TO INCLUDE PICTURES ALONG WITH THE
WORDS.	WELL, FONTRIX CAN DO THIS.  THERE IS THIS THING CALLED A GRAPHIC; WHICH
IS JUST A FANCY WORD FOR A HI-RES PICTURE (YOU KNOW, THE KIND YOU SAVE AT $2000
AND $2000).  IF YOU HAVE A SPECIFIC PICTURE THAT YOU WANT TO LOAD, JUST USE THE
COMMAND THAT LOADS THE GRAPHIC, AND MAKE SURE THAT YOU ARE ALREADY POSITIONED
IN YOUR GRAFILE (WHICH SHOULD ALREADY BE OPEN AND READY) SO THAT WHEN THE
PICTURE IS LOADED, IT WILL LOAD INTO THE SPOT IN YOUR GRAFILE THAT YOU WANT IT
TO.  THIS WAY YOU COULD LOAD ABOUT 16 SCREENS ACCROSS AND ABOUT THE SAME DOWN
WORTH OF GRAPHIC PICTURES AND PRINT THEM ALL OUT AT THE SAME TIME!  THIS
SPECIAL FEATURE CAN BE VERY USEFUL ONCE YOU FIND THE USE.

----------*
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
