------------------------------------------------------------------------------
			  G.P.L.E.  DOCUMENTATION
			   ENTERED BY: JUDIE MAC


PLE.48 LOCATES ITSELF BETWEEN DOS AND ITS BUFFERS, MOVING HIMEM DOWN BY 4K.
PLE.LC IS USED WITH THE ALTERNATE BASIC ON THE RAM CARD.  PLE.DM IS USED WHE N
YOU HAVE DOS ON THE RAM CARD.  (TO BE USED WITH DOS MOVER)



EDIT MODE:

"<-,->" = ARROW KEYS MOVE THE CURSOR BACKWARD AND FORWARD IN A LINE.  THEY MAY
BE USED WITH THE REPT (REPEAT KEY) FOR SPEED.

CONTROL I = INSERTS CHARACTERS BEFORE THE CURRENT CURSOR POSITION.  AS YOU
INSERT CHARACTERS, THE REMAINDER OF THE LINE MOVES TO THE RIGHT TO MAKE ROOM.
ANOTHER EDIT MODE COMMAND WILL CANCEL INSERT.

CONTROL D = DELETES THE CHARACTER AT THE CURRENT CURSOR POSITION.  THE REMAINDE
R OF THE LINE MOVES TO THE LEFT AS YOU DELETE EACH CHARACTER. CTRL-D WITH THE R
EPT KEY QUICKLY DELETES MULTIPLE CHARACTERS.

CONTROL B = PLACES THE CURSOR AT THE BEGINNING OF THE LINE YOU ARE EDITING, OVE
R THE FIRST CHARACTER OF THE LINE NUMBER. THIS COMMAND CAN ALSO REPOSITION THE
CURSOR FOR A FIND COMMAND, AND FOR RENUMBERING LINES. (NOTE* WHEN YOU RENUMBER
A LINE, THE OLD LINE NUMBER STILL EXISTS!!)

CONTROL N = PLACES THE CURSOR ONE PLACE TO THE RIGHT OF THE LAST CHARACTER OF T
HE LINE. THIS COMMAND IS HANDY FOR EDITING CHARACTERS NEAR THE END OF A LINE.

CONTROL O = THE OVERRIDE COMMAND, WORKS THE SAME AS CTRL-I, EXCEPT THAT THE FIR
ST INSERTED CHARACTER MAY BE A CONTROL CHARACTER. AFTER ACCEPTING THE FIRST CHA
RACTER, THIS COMMAND FUNCTIONS EXACTLY LIKE CRTL-I. OVERRIDE IS USEFUL FOR INSE
RTING A CTRL-D INTO A DOS COMMAND AND/OR FOR IMBEDDING OTHER CONTROL CHARACTERS
 INTO REM AND PRINT STATEMENTS.

CONTROL F = THE FIND COMMAND, FOLLOWED BY A CHARACTER TYPED "N" TIMES, WILL LOC
ATE AND MOVE THE CURSOR TO THE N'TH OCCURRENCE OF THAT CHARACTER IN THE LINE. T
O FIND THE 4TH "P" IN A LINE, TYPE CTRL FPPPP. THIS RAPIDLY MOVES THE CURSOR TO
 THE CORRECT POSITION.

CONTROL Z = THE ZAP COMMAND,FOLLOWED BY A CHARACTER TYPED "N" TIMES, DELETES AL
L CHARACTERS UP TO THE N'TH OCCURRENCE OF THAT CHARACTER.

CONTROL R = THIS IS THE RESTART COMMAND. IT RESTORES THE LINE YOU ARE EDITING T
O ITS PRE-EDITED STATE. YOU MUST ENTER THIS COMMAND BEFORE HITTING RETURN. REST
ART IS VERY HANDY FOR RESTORING CHARACTERS YOU MISTAKENLY DELETED OR ZAPPED.

CONTROL P = PACKS A LINE BY REMOVING EXTRANEOUS SPACES.

CONTROL C = CONVERTS UPPER CASE CHARACTERS TO LOWER CASE AND VICE-VERSA. CONTRO
L C WITH THE REPT KEY SPEEDS UP THE CONVERSION.(SEE NOTE ON UPPER/LOWER CASE BE
LOW)

CONTROL Q = DELETES ALL CHARACTERS FROM THE CURRENT CURSOR POSITION TO THE END
OF THE LINE, AND THEN "EXITS" EDIT MODE.

CONTROL X = CANCELS THE LINE YOU ARE EDITING AND "EXITS" EDIT MODE.

CONTROL M = THIS IS THE SAME AS RETURN. IT TERMINATES EDIT MODE AND SAVES THE M
ODIFIED LINE.

CONTROL A = THIS CONTROLS UPPER AND LOWER CASE MODES.


UPPER/LOWER CASE:


  G.P.L.E.  SUPPORTS BOTH LOWER CASE ADAPTERS AND A VARIETY OF 80 COLU MN VIDEO
BOARDS.  G.P.L.E.  CONVERTS APPLESOFT,DOS, AND MONITOR COMMANDS IN LOWER CASE
TO UPPER CASE.	G.P.L.E.  ALSO SUPPORTS THE VERY POPULAR "SHIFT-KEY MODIFIC
ATION" WHICH MAKES ENTERING UPPER AND LOWER CASE A SNAP.  CONTROL A PLACES YOU
I N LOWER CASE MODE; HOWEVER,LOWER CASE IS NOT TURNED OFF BY HITTING THE RETURN
K EY.  YOU REMAIN IN LOWER CASE MODE UNTIL YOU TYPE ANOTHER CONTROL A.	ONCE IN
LOW ER CASE MODE, A SINGLE CONTROL A PUTS YOU IN UPPER CASE MODES FOR THE NEXT
CHAR ACTER ONLY.  TYPING CONTROL A "TWICE"(CONSECUTIVELY) PLACES YOU IN UPPER
CASE.


GLOBAL EDIT COMMAND:

  A GLOBAL EDIT COMMAND DISPLAYS EACH LINE REQUESTED OR FOUND BY A SE ARCH, ONE
AT A TIME.  AS EACH LINE IS DISPLAYED, YOU ARE PLACED IN EDIT MODE WIT H THE
OPTION TO FURTHER MODIFY THE LINE, PROCEED TO THE NEXT LINE, OR EXIT GLOB AL
EDIT MODE PREMATURELY.	TO AVOID ENTERING EDIT MODE FOR EACH LINE, USE THE FA
ST OPTION (/F) ON THE GLOBAL EDIT COMMAND LINE.  THIS PERFORMS A QUICK GLOBAL
SE ARCH AND REPLACE, OR LISTS ALL LINES WHERE A CERTAIN STRING EXISTS.	FOR
EXAMPLE , CTRL E "POKE"/F QUICKLY LISTS ALL LINES CONTAINING THE KEYWORD
"POKE".


EXAMPLES:

CONTROL E L1,L2,"STRING1","STRING2"/O


L1	   = STARTING LINE NUMBER
L2	   = ENDING LINE NUMBER
STRING1   = SEARCH STRING (16 CHAR.MAX)
STRING2   = REPLACEMENT STRING (16 CHAR.MAX)
O	   = OPTION: R=RAW SEARCH, F=FAST SEARCH

HOW LINE SHOULD BE TYPED:

CONTROL E 100,150  = EDIT LINES 100 THRU 150
CONTROL E 10,50,"POKE" = EDIT ALL LINES BETWEEN 10 AND 50 WHICH CONTAIN THE STR
ING "POKE"
CONTROL E "READ","WRITE" = REPLACE EVERY OCCURRENCE OF "READ"  IN YOUR PROGRAM
WITH THE STRING "WRITE"


ALL OF THE ARGUMENTS DEFINED ABOVE ARE OPTIONAL. STRING1 AND STRING2 MUST BE EN
CLOSED IN QUOTES (" "). TO IMBED QUOTES IN THESE STRINGS, YOU MUST DOUBLE THE I
MBEDDED QUOTES. FOR EXAMPLE, IF YOU WANTED TO SEARCH FOR THE STRING "ENTER",STR
ING1 WOULD BE """ENTER""".A SEARCH STRING WILL BE IGNORED IF IT IS A
SUBSTRING OF A LARGER STRING. FOR EXAMPLE, THE SEARCH STRING "O" WILL NOT MATCH
 THE "O" IN THE KEYWORD "POKE". G.P.L.E. WILL FIND THESE SUBSTRINGS WITH THE RA
W SEARCH (/R) OPTION ON THE GLOBAL EDIT COMMAND LINE(E.G. CONTROL E "O"/R)


PAGE LIST COMMAND   YOU STILL USE CONTROL S TO STOP AND START A LISTING OR CATA
LOG, AND CONTROL C  TO TERMINATE A LISTING. CONTROL P (PAGE LIST) HALTS A LISTI
NG AND EACH SUBSEQUENT CONTROL P DISPLAYS THE NEXT 20 LINES FO THE LISTING.




ESCAPE FUNCTIONS:


ESC 1 - CATALOG DRIVE 1
ESC 2 - CATALOG DRIVE 2
ESC L - LIST PROGRAM-HIT ESC TO STOP/HI
T ESC TO START AGAIN
ESC U - USR FUNCTION
ESC T - TEXT (POKE -16300,0)
ESC R - RUN
ESC W - BEGINNING AND END OF LAST BINAR
Y LOADED FILE
ESC * - MONITOR
ESC 0 - CALL 936 - CLEAR SCREEN TO TOP
ESC / - PRINT SYMBOL (?)
ESC Q - MEMORY CONTENTS
ESC S - SECTORS FREE
ESC H - DISPLAY CONTROL CHARACTERS
ESC V - VTAB 1
ESC M - RETURN
ESC N - CLEAR,START,STEP,FROM,TO

TO SEE WHAT ESCAPE FUNCTIONS ARE IN THE ESC MENU, BRUN ESCAPE PRINTER ON DISK.
ALSO YOU CAN CREATE YOUR OWN ESC FUNCTIONS.
---------------------------------------
