

           vOICE mAIL hACKING
           ----- ---- -------

pART 1: bRIEF sUMMARY
---- -- ----- -------

aLONG ABOUT 2 YEARS AGO, i WOULD DO
JUST ABOUT ANYTHING TO GET MY OWN vMB.
i WOULD ALMOST SELL MY SOUL FOR ONE.
bUT ALAS, AT THE TIME ALMOST NO ONE
WAS GIVING ANY AWAY AND i HAD NOTHING
WORTHY TO TRADE. sO, i STARTED HACKING
MY OWN. aT FIRST i HACKED PEOPLE'S
BOXES, GUESSING THEIR PASSCODES. tHIS
OF COURSE IS STUPID, BECAUSE ALL THEY
HAVE TO DO IS ALERT THE SYSTEM MANAGER
AND POOF, NO MORE MAILBOX. sO, AFTER i
HAD EXPERIANCED THAT, i STARTED TO
DISCOVER THAT NO ONE MISSED EMPTY
BOXES. aND HERE i AM TODAY - WRITING A
FILE TO TEACH MOST OF YOU WHAT i KNOW
NOW. sO LET'S BEGIN, SHALL WE?

tHE FIRST STEP TO HACKING ANYTHING -
ANYTHING AT ALL - IS TO KNOW WHAT
YOU'RE HACKING. tHE SAME APPLYS TO
vMB HACKING. sO, LET ME START OFF BY
DESCRIBING SOME OF THE PROMINANT VOICE
MAIL SYSTEMS.

aDR
---

tHESE ARE THE FAMILIAR MAILBOXES THAT
i AM SURE ALL OF YOU HAVE CALLED ONCE
IN YOUR LIFE. tHESE ARE THE SYSTEMS
WHERE YOU HEAR SOME CHEESY GREETING,
HIT "*" TWICE, AND THEN ENTER THE
MAILBOX NUMBER. wHEN YOU FIRST PRESS
THE "*", THE SYSTEM THINKS THAT YOU
OWN THAT MAILBOX AND ARE ENTERING IT.
sO, IT WILL REPLY WITH "hELLO XXXX,
PLEASE ENTER YOUR PASSCODE." sO YOU
HIT "*" A SECOND TIME AND ABORT IT,
AND FIND YOURSELF PLOPPED AT THE MAIN
MENU, WITH THE FRIENDLY GREETING OF
"wELCOME TO THE MESSAGE CENTER." sOME
NOTES ON THIS SYSTEM IS THAT BOXES ARE
USUALLY (SOMETIMES NOT) 4 DIGITS IN
LENGTH - AS ARE THE PASSCODES. tHE
MESSAGE LENGTH IS USUALLY PRETTY NICE,
ANYWHERE FROM 1-5 MINUTES. bUT OF
COURSE THIS ALL DEPENDS ON THE NAZI
SYSTEM MANAGER. aNYWAY. aDR'S ARE GOOD
LITTLE SYSTEMS. eASY TO HACK - EASY TO
USE.

aSPEN
-----

i'M SURE THAT EVERYONE HAS AT ONE TIME
CALLED THIS, TOO. iF THERE IS NO
SYSTEM GREETING, YOU WILL BE WELCOMED
WITH "hELLO, THIS IS aSPEN. tHE
AUTOMATED SPEECH EXCHANGE NETWORK."
pRETTY SELF-EXPLANATORY, IS IT NOT? iF
THERE IS A SYSTEM GREETING SET-UP, YOU
WILL HAVE TO PRESS "*" ONCE TO SKIP
THAT. yOU WILL THEN HEAR "pLEASE DIAL
THE NUMBER OF THE PERSON YOU'RE
CALLING. iF YOU HAVE A MAIL BOX ON
THIS SYSTEM, PLEASE PRESS POUND."
aSPEN'S ARE CLEAR GIVE-AWAYS. bOXES
ARE EITHER 3-4 DIGITS, PASSCODES 4-5
OR LONGER. hOWEVER, i HAVE NEVER SEEN
ANY LARGER THEN 5 DIGITS, BUT THEY CAN
BE EXPANDED TO AS MUCH AS 9. mESSAGE
LENGTH IS USUALLY AROUND THE 1 MINUTE
RANGE, DEPENDING ON WHAT MAILBOX YOU
HACK. i HAVE ONE CURRENTLY ON AN aSPEN
THAT IS UP AROUND THE 8 MINUTE RANGE,
BUT THAT'S JUST BECAUSE IT'S LIKE A
"cOSYSOP" BOX. iT CAN DO LIMITED
SYSTEM MANAGER FUNCTIONS. aNYWAY.
fRIENDLY SYSTEM, EASY TO HACK.

gENESIS
-------

oK, i WOULD SUPPOSE. wHEN YOU CALL,
YOU'LL BE GREETED WITH (USUALLY) "gOOD
XXXX. pLEASE ENTER THE MAILBOX NUMBER
YOU WISH". tHE "#" KEY TAKES YOU TO A
DIRECTORY, WHERE YOU CAN JUST HIT THE
FIRST LETTER (a,b,c,ETC.) OF SOMEONES
NAME TO HEAR THEIR MAILBOX NUMBER. oF
COURSE, a b & c ARE ALL ON THE SAME
NUMBER, 2, SO THAT IS EVEN EASIER.
jUST SCRIBBLE DOWN SOME BOX NUMBERS -
THEY MAY BE WORTH PLAYING AROUND WITH.
aFTER ALL, IT'S ALWAYS FUN TO DELETE
SOMEONE ELSE'S VOICE MAIL. iF YOU
PRESS "*" IT WILL USUALLY ADJUST THE
VOLUME, OR JUST ABORT TO WHATEVER.
bOXES ARE 3-4 DIGITS, 3 IS MORE
PROMINANT. pASSCODES ARE USUALLY 3-4,
WITH 4 BEING THE MORE FREQUENT CHOICE.
wHILE YOU ARE LISTENING TO SOMEONE'S
GREETING, YOU CAN PRESS "0" TO ENTER
THE PASSCODE FOR THAT MAILBOX.
oVERALL, IT'S OK. nOT THE GREATEST,
BUT NOT THE WORST EITHER.

pART 2: lOCATING aN eMPTY bOX
---- -- -------- -- ----- ---

tHIS IS, FOR THE MOST PART, THE MAJOR
STEP TO vMB HACKING. fOR IF YOU CAN'T
FIND AN EMPTY, YOU'LL PROBABLY LOSE
YOUR BOX THE NEXT BUISNESS DAY.
aNYWAY. tHE MAIN PAIN-IN-THE-ASS ABOUT
vMB HACKING IS THAT AFTER 3 INVALID
TRYS THE SYSTEM USUALLY HANGS UP ON
YOU. tO MAKE YOUR JOB EVEN HARDER,
THEY USUALLY SPACE OUT BOXES, LEAVING
LITTLE GAPS OF 3 OR 4 IN BETWEEN. tHAT
WAY IF YOU SCAN STRAIGHT THROUGH YOU
•äEP WUU ÍâIUßT©
9ÅGET
DISCOURAGED. bUT OF COURSE, THERE IS
A WAY AROUND THAT NASTY LITTLE
FEATURE. aLL SYSTEMS HAVE A NIFTY
LITTLE "aBORT" KEY. iT'S USUALLY "*"
OR "#", AND IT TAKES YOU OUT OF ALMOST
ANY SITUATION. tHAT COMES IN VERY,
VERY HANDY WHILE YOU ARE LOOKING OVER
THE SYSTEM FOR AN EMPTY BOX. lET ME
PASS ON SOME TRICKS FOR EACH SYSTEM.

aDR
---

sO, YOU HAVE NOW FOUND YOURSELF AN
adr. yOU ARE AT THE "wELCOME TO THE.."
PROMPT. tHINGS TO REMEMBER ARE THAT
BOXES USUALLY START AT 1000 OR 2000,
AND THERE IS ALMOST ALWAYS A SYSTEM
MAILBOX SOMEWHERE IN THE 9000 RANGE,
USUALLY AT 9999. (tHAT APPLYS FOR
EVERY SYSTEM, SAVE THAT SOME SYSTEMS
MAY BE 3 DIGIT BOXES, SO CHOP A DIGIT,
THAT'S ALL.) nOW, TO DEFEAT THAT NASTY
LITTLE 3 TRY HANG-UP, YOU MUST FIRST
FIND YOURSELF A GOOD BOX. iT DOSEN'T
MATTER WHOSE - EMPTY OR NOT. lOOK IN
THE COMMON PLACES, EXPLAINED ABOVE. aS
SOON AS YOU FIND ONE, JOT IT DOWN. nOW
YOU CAN SCAN FREELY AND AFTER EVERY 2
BAD TRYS JUST PUNCH UP THE GOOD BOX,
ABORT OUT OF THAT AND SCAN SOME MORE.
sO, OK. lET'S SAY YOU FIND A GOOD
MAILBOX. yOU'LL BE HEARING THE
GREETING. hIT "*" TWICE, YOU'RE BACK
AT THE "wELCOME TO THE.." PROMPT. nOW
YOU CAN SCAN 2 MORE INVALID TRYS
WORTH. a HINT IS THAT EMPTY BOXES ARE
ALWAYS, AND i MEAN ALWAYS, AT THE END
OF THE GOOD BOXES. tO SAVE TIME i
SUGGEST SCANNING BY 100'S. oF COURSE,
GOING BACKWARDS ONCE IN AWHILE A FEW
DIGITS.. aNYWAY. wHEN YOU FIND AN
EMPTY MAILBOX, INSTEAD OF A GREETING
YOU'LL HEAR "mAILBOX XXXX" OR
SOMETHING. hIT "*" ONCE, AND YOU'LL
HEAR "hELLO MAILBOX XXXX, PLEASE ENTER
YOUR PASSCODE." wHALLA, YOU HAVE
LOCATED AN EMPTY. wRITE THE NUMBER
DOWN, HIT "*" AND SCAN BY ONES ABOVE
AND BELOW THE NUMBER. tHERE IS NEVER
JUST ONE.

aPSEN
-----

tHE EASIEST WAY TO SCAN aSPEN'S IS TO
PRETEND YOU'RE GOING TO ENTER YOUR
MAILBOX. hIT "#", THEN A PROBABLE
MAILBOX NUMBER, AS i OUTLINED IN THE
aDR'S ABOVE. oNCE YOU FIND ONE, YOU'LL
HEAR SOMETHING LIKE "jOHN dOE, PLEASE
ENTER YOUR PASSWORD." tHE NAME WILL BE
IN THE OWNER'S VOICE - JUST TO MAKE
EVERYTHING NICE AND FRIENDLY. hIT "*"
AND SCAN AROUND. wHEN YOU FIND AN
EMPTY, YOU'LL HEAR SOMETHING LIKE
"mAILBOX XXXX, PLEASE ENTER YOUR
PASSCODE." tHE REST IS BASICALLY THE
SAME AS THE aDR'S. wRITE IT DOWN, SCAN
AROUND. gEE, THIS IS SURE FUN, ISN'T
IT?

gENESIS
-------

wELL, YOU GET THE GOOFY PROMPT ON
THIS, AND THE EASIEST WAY IS JUST TO
HIT "#" AND THEN "2" AND WRITE DOWN
SOME NUMBERS. oR, YOU COULD DO 2-9 AND
FIND THE HIGHEST NUMBER. tHEN SCAN
JUST ABOVE THAT FOR EMPTYS. wHEN YOU
ENTER SOMEONE'S BOX, YOU'LL HEAR THEIR
GREETING. hIT "0", THEN HIT "#" TO
ABORT. aS ALWAYS, REMEMBER THE 3
STRIKES RULE, AND KEEP GOING BACK TO A
GOOD BOX AFTER 2 FAULTY TRIES. wHEN
YOU LOCATE AN EMPTY, THE GREETING WILL
BE "i'M TAKING A MESSAGE FOR mMAILBOX
XXXX." hIT "0". tHEN YOU'LL HEAR
SOMETHING LIKE "pLEASE ENTER YOUR
PASSWORD." pRETTY EASY, EH? dO THE
ROUTINE.. wRITE IT DOWN, SCAN AROUND.

pART 3: hACKING tHE eMPTY bOX
---- -- ------- --- ----- ---

wELL, NOW YOU HAVE YOUR EMPTY'S ALL
WRITTEN DOWN AND ARE READY TO JUMP
INTO THEM. tHE THING TO KEEP IN MIND
HERE IS TO KEEP IT SIMPLE! nO ONE
WANTS TO BE TROUBLED WITH REMEMBER A 9
DIGITS TOTALLY RANDOM PASSCODE. tHEY
WANT SOMETHING SMALL AND SIMPLE, LIKE
A 4 DIGIT YEAR. rEMEMBER - THINK
STUPID. tHE SYSTEM MANAGER IS USUALLY
ABOUT AS SMART AS A SNAIL IN A BOWL
FULL OF jELLO. hE WANTS TO WORK LEAST
OF ALL - SO HE'LL MAKE THE EMPTYS UP
WITH CHEESY PASSCODES.

aDR
---

tHIS IS A BALL-BUSTER TO HACK. yOU GET
3 PASSCODE TRYS, THEN YOU GET DUMPED.
aFTER YOU ENTER ONE PASSCODE, THAT'S
IT - YOU CAN'T ABORT ANYMORE. bUT YOU
CAN (SOMETIMES) HIT "*" RIGHT WHEN IT
SAYS "gOODBYE" AND FIND YOURSELF BACK
AT THE "wELCOME TO THE.." PROMPT. sO
PLAY AROUND SOME. rEMEMBER, PASSCODES
ARE SIMPLE. dON'T BEAT YOUR HEAD IN
TRYING TO GUESS SOME OUTRAGEOUS PASS,
JUST SCAN ANOTHER SYSTEM AND MOVE ON.
pASSCODES ARE USUALLY THE SAME AS THE
MAILBOX NUMBER, THE CURRENT YEAR,
1234, 0, OR THEY SOMETIMES DON'T HAVE
ONE AT ALL. sO, PLAY WITH IT.

aSPEN
-----

aSPEN'S ARE ALWAYS FUN. tHE PASSCODES
ARE 3 OR 4 DIGITS, AND USUSALLY NO
LONGER - THUS MAKING IT A FUN LITTLE
JOB TO PULL OFF. oN MOST SYSTEMS AFTER
2 BAD PASSCODES YOU CAN JUST ABORT OUT
OF THE BOX, AND THEN DO IT AGAIN. oF
COURSE, ON EMPTY BOXES YOU NEED NOT
WASTE YOUR TIME WITH 4 BILLION TRYS,
SO WHY BOTHER. pASSCODES ARE SIMPLE,
AS ON aDR'S, AND ALMOST EVERY OTHER
SYSTEM FOR THAT MATTER. rEMEBER, THINK
STUPID.

gENESIS
-------

sAME AS ABOVE, BUT THERE IS A LITTLE
TRICK. mOST EMPTY BOXES HAVE PASSCODES
SET TO "0", SO TRY THAT FIRST. aND i
CAN'T STRESS THIS ENOUGH, THINK SIMPLE
FOR CHRIST'S SAKE!

pART 4: aFTERMATH
---- -- ---------

oNCE YOU ACHEIVE A BOX, YOU CAN
BASICALLY FIGURE IT OUT FROM THERE. iF
YOU'RE HAVING TROUBLE FINDING EMPTYS
ON ONE SYSTEM, OR THE EMPTYS HAVE
TWISTED PASSCODES, DROP THAT SYSTEM.
sCAN YOURSELF ANOTHER. tHEY'RE ALL
OVER THE DAMN PLACE.

oF COURSE, i KNOW YOU'RE ALL SITTING
OUT THERE ASKING "dUH, WHY ARE THERE
EMPTYS ANYHOW?" wELL LOOK AT THE HUMAN
RACE AS A WHOLE. wE ARE LAZY, EACH AND
EVERY ONE OF US. wHO IN GOD'S NAME
WANTS TO SIT THERE EVERY OTHER SECOND
AND SPRINT TO MAKE A NEW BOX FOR SOME
NEW EMPLOYEE? nO ONE, THAT'S WHO. sO,
THE SYSTEM MANAGER SETS UP 5-10 BOXES
FOR FUTURE EXPANSION. hE SETS THE
PASSCODES REAL CHEESY-LIKEM, SO THAT
Ò¨EN XM$WKU§B%MÅ2ND GRADE EDUCATION
CAN REMEMBER THEM FOR LONG PERIODS OF
TIME. sO, THINK SIMPLE. tHINK LIKE A
MORON. tHINK LIKE A MAN WHO HANGS OUT
AT THE WATER-COOLER AND SELLS CHEESY
HOUSES FOR A LIVING.

pART 5: cLOSING
---- -- -------

sOME NOTES. iF YOU SHOULD HAPPEN TO
STRAY ACROSS THE SYSTEM MANAGER
PASSCODE, dont change anything, LEAST
OF WHICH THE PASSCODE. jUST MAKE A FEW
BOXES IN A NICE SHADY CORNER OF THE
SYSTEM AND KEEP A LOW PROFILE. iF THE
MANAGER CAN'T GET INTO HIS OWN
MAILBOX, HE'LL KNOW SOMETHING'S UP FOR
SURE AND GO LOOKING AROUND.
 
tO BETTER HELP YOU IDENTIFY THESE
SYSTEMS, CALL THESE. tRY TO REMEMBER
THE VOICE, TOO. tHEY ARE CLEAR
GIVE-AWAYS.

aDR
--- 
1-800-326-5477
(24 hOURS, sYSTEM BOX AT 5000.)

aSPEN
-----
1-800-800-1239
(24 hOURS, sYSTEM BOX AT 9999. hIT "*"
THEN BOX NUMBERS.)

gENESIS
-------
1-800-999-2328
(24 hOURS, bOXES START AT 200 AND GO
UP.)

wELL, HAVE FUN. aND DON'T GIVE ALL
YOUR FRIENDS TOO MANY MAILBOXES NOW,
EH? 

aND REMEMBER - DON'T WASTE YOUR TIME
ON AN OLD SYSTEM. tHE NEWER, THE
BETTER. tHE OLD ONES HAVE BEEN HACKED
TO HELL AND BACK, AND THE MANAGERS
MAKE EVERYTHING DIFFICULT. sCAN
EXCHANGES LIKE MAD, GATHER VIRGIN
SYSTEMS, HACK THEM. tHEY DON'T KNOW
WHAT THEY'RE UP AGAINST, SO THEY MAKE
EVERYTHING NICE AND FRIEDNDLY. nICE AND
OPEN. nICE AND EASY.

wELL, LATERS.

                          -hAIRY lEECH

tYPED ON 2/22/91.

sUPPORT THE FOLLOWING:

fALL0UT
[206]862-2086
bEST iN tHE sTATES..

sOCIAL dISTORTION
[908]303-0927
kICKING mAJOR aSS..


mATRIX
[908]905-6691


