=-=-=-= The Realm Of The Rogues =-=-=-=
	    (415)  941-1990

		   ***	D R A G O N ' S   L A I R  ***
		 ---------------------------------------
		 --- COMPILED BY THE IRISH ROGUE     ---
		 ---------------------------------------

  COPYRIGHT (C) - 1983

THE SOLUTION LEGEND --

    S - SWING DIRK'S SWORD
    F - MOVE THE JOYSTICK FORWARD
    B - PULL THE JOYSTICK BACKWARDS
    L - MOVE THE JOYSTICK TO THE LEFT
    R - MOVE THE JOYSTICK TO THE RIGHT
  (R) - THE ROOM CAN BE REVERSED BY THE COMPUTER.  EACH LEFT MOVE MUST BE
CHANGED TO A RIGHT AND VICE VERSA.  FORWARD, BACKWARDS AND SWORD REMAIN THE
SAME.

  (H) - A HINT GIVING TIPS ON TIMING OR HOW TO SPOT ROOMS THAT HAVE BEEN
REVERSED.

---------------------------------------

  IN DRAGONS LAIR DIRK (YOU) MUST CORRECTLY NAVIGATE EACH OF THE ROOMS ONCE.
ROOMS THAT CAN BE REVERSED MUST BE COMPLETED ONCE REGULAR AND ONCE REVERSED.
THE ELEVATOR IS AN EXCEPTION TO THE RULE AS YOU MUST COMPLETE THE NORMAL
ELEVATOR SIX TIMES AND THE REVERSED SCREEN ONCE.  ONLY AFTER YOU HAVE DONE THIS
WILL YOU REACH YOUR GOAL...  THE DRAGONS LAIR...  WHEN THERE YOU MUST KILL THE
DRAGON AND THEN THE GAME ENDS...

---------------------------------------

  THERE ARE TWO SECRETS NEEDED TO SOLVE DRAGONS LAIR..	ONE INVOLVES LISTINING
AND THE OTHER INVOLVES TIMING AND WATCHING.  THE FIRST IS LISTINING.  EACH TIME
YOU MOVE THE DRAGONS LAIR JOYSTICK ONE OF THREE AUDIBLE RESPONSES OCCURS.  ONE,
NO SOUND AT ALL.  TWO, A LOW FREQUENCY BUZZ EMINATES FROM THE SPEAKER, OR THREE,
A HIGH PITCHED "DING" COMES FROM THE SPEAKER.  EACH tone (or lack of tone) means
something.  the first (no sound) means that no movement at that time is needed
so none is looked for by the computer.	it simply doesen't know you moved the
joystick.  the second "buzz" sound TELLS YOU THAT THE COMPUTER DOES NOT ACCEPT
THE MOVE...  (YET) OFTEN THIS IS CAUSED BY A TIMING PROBLEM AND ANOTHER MOVEMENT
IN THAT DIRECTION WILL OFTEN CORRECT THIS.  THE THIRD SOUND IS THE "BEEP".  THIS
SOUND MEANS THAT THE COMPUTER HAS ACCEPTED YOUR MOVE.  IT DOES NOT MEAN THAT IT
IS WRONG OR RIGHT.  JUST THAT IT HAS BEEN REGISTERED.  MANY TIMES I HAVE BEEN
KILLED AND REALIZED I WASN'T LISTENING FOR THE BEEP.  I CANNOT OVEREMPHASIZE THE
IMPORTANCE OF THESE SOUNDS.

  THE OTHER IMPORTANT THING TO LEARN ABOUT DRAGONS LAIR IS THAT IN SOME OF THE
ROOMS, THE DESIGNERS MAKE PARTS OF THE SCREEN FLASH (A DOORWAY FOR EXAMPLE).
THIS IS OFTEN USED TO HELP THE PLAYER THROUGH A DIFFICULT SCREEN.  THIS IS NOT
ALWAYS THE CASE AS IN A FEW ROOMS IN THE GAME THE FLASH SHOWS THE WRONG WAY (AND
YOU THOUGHT THIS WAS EASY!).  OFTEN I WILL GIVE YOU TIMING HINTS BASED UPON THE
FLASHES.  USUALLY YOU WILL BE MOVING IN THE DIRECTION OF THE FLASH DIRECTLY
AFTER YOU SEE IT.

---------------------------------------

  EACH ROOM HAS A DESCRIPTIVE TITLE WHICH WILL ALLOW YOU TO DETERMINE THE ROOM
PATTERN YOU NEED.  THE ROOMS ARE ALWAYS PLAYED IN A SEMI-RANDOM PATTERN.

---------------------------------------
  ROOM #1:  THE ROOM WITH THE BRICK WALL FORMING IN FRONT OF YOU.

MOVEMENT -- F.
  (H) -- YOU MUST VERY QUICKLY MOVE FORWARD TO MAKE IT THRU THE WALL.  THIS IS
NOT DIFFICULT TO DO IF YOU ARE PREPARED....

---------------------------------------
  ROOM #2:  THREE ROPES SWINGING OVER THE FIRE PITS.

MOVEMENT -- R-R-R-R.
  (H) -- THE FIRST JUMP SHOULD BE MADE WHEN THE ROPE NEAREST TO YOU IS CLOSE TO
YOU.  OTHER JUMPES ARE MADE WHEN DIRK REACHES HIS HAND OUT TO GRASP THE NEXT
ROPE.  (YOU WILL NOT SEE THE NEXT ROPE YET...)

  (R) -- THIS ROOM CAN BE REVERSED.  YOU MUST MOVE INSTEAD L-L-L-L TO CROSS THE
PIT.  IT IS FAIRLY OBVIOUS TO SPOT THIS ROOM REVERSED AS DIRK APPEARS ON THE
LEFT SIDE OF THE SCREEN WHEN IT IS NORMAL AND ON THE RIGHT WHEN IT IS REVERSED.

---------------------------------------
  ROOM #3:  THE ROOM WHERE ROCKS FALL ONTOP OF YOU.

MOVEMENT -- R-R
  (H) -- MOVE RIGHT AS SOON AS YOU RECOGNIZE THE ROOM AND AGAIN AFTER THE FLASH
IN THE RIGHT-HAND DOORWAY (SEE BEGINNING ABOUT FLASHES).

---------------------------------------
 ROOM #4:  DRINK ME ROOM.

MOVEMENT -- R
  (H) -- MOVE RIGHT AS SOON AS YOU ENTER THE ROOM.  THIS IS AN EXAMPLE OF THE
ROOMS IN WHICH FLASHES ARE NOT SHOWING THE CORRECT PATH.

---------------------------------------
  ROOM #5:  THE ROOM WITH JUMPING SKULLS OOOZING TAR, AND BIG HANDS.

MOVEMENT -- F-S-F-S-L-s
  (H) -- MOVE FORWARD AS SOON AS YOU SEE THE SKULLS (BE SURE TO LISTEN FOR THE
"BEEP").  PRESS SWORD WHEN DIRK LANDS FROM HIS JUMP FORWARD.  CONTINUE THROUGH
THE ROOM NORMALLY FROM HERE (LISTEN CAREFULLY AS THIS IS A NOISY ROOM.)

  (R) -- THE ROOM CAN BE REVERSED.  ONLY ONE MOVE IN THIS ROOM MUST BE CHANGED
TO ACCOUNT FOR THE SWITCH AND THAT IS THE MOVE AFTER DIRK SWINGS THE SECOND
TIME.  SIMPLY LOOK WHICH WAY HE IS FACING AFTER HE SWINGS AND MOVE THAT WAY.
(NOT TERRIBLY DIFFICULT IS IT..)

---------------------------------------
ROOM #6:  BREATHING DOOR WITH DIAMOND.

MOVEMENT -- R-R
  (H) -- MOVE RIGHT WHEN DIRK GETS PULLED INTO SECOND ROOM AND RIGHT AGAIN WHEN
THE DOORWAY ON THE RIGHT SIDE FLASHES.

---------------------------------------
  ROOM #7:  DUNGEON WITH SKULL HANGING FROM A ROPE.

MOVEMENT -- S-S-S-F
  (H) -- SWING FIRST THREE TIMES AND KILL SNAKES.  DIRK WILL ALWAYS MISS THE
THIRD SNAKE.  AFTER HE SWINGS THE SWORD THE THIRD TIME PUSH FORWARD QUICKLY
AGAIN AS DIRK ESCAPES THE DUNGEON.

---------------------------------------
  ROOM #8:  ROOM WITH GREEN TENTACLE REACHING IN THRU TOP LEFT OF SCREEN.

MOVEMENT -- S-F-R-B-L-F
  (H) -- AFTER YOU SWING THE FIRST TIME YOU MUST WAIT FOR A FLASH IN FRONT OF
DIRK.  AS SOON AS YOU SEE THE FLASH MOVE THAT DIRECTION.  DIRK WILL END UP ON A
STOOL AFTER HE MOVES LEFT.  THEN YOU MUST JUMP THRU THE DOOR THAT IS OPENING AND
CLOSING HE MUST JUMP WHEN IT IS OPEN.  YOU WILL ONLY GET 2 CHANCES AT THIS.

---------------------------------------
  ROOM #9:  DUNGEON WITH LIGHTNING AND FIRE.

MOVEMENT -- R-F-B-L
  (H) -- IN THIS ROOM THE LIGHTNING ACTS AS THE POINTER TELLING YOU WHEN TO
MOVE.  AFTER THE FIRST BOLT OF LIGHTNING make the first move.  same for the
second and third.  after the third is complete move left and dirk will exit
(exit stage left!).

---------------------------------------
  room #10:  rowboat with rapids and whirlpools

movement -- r-l-r-l-r-l....ect...ect
  (h) -- this is a very easy room due to the fact that all you must do is follow
the flashes in the beginning, go to the light colored sections in the middle and
avoid all whirlpools.  the room is even easier since the movements switch
between right and left at each decision so after you have the first move in a
set, the rest are easy!  be aware of tricks like playing a screen where you do
nothing followed quickly by a decision screen.	only one move other than r or l
is needed.  after the whirl- pools end, simply wait for dirk to be shot out of
his boat and move forward to grab the chain.  i will leave the rest of the room
to you (i promise it's an easy one)

  (r) -- there is one strange happening on this screen.  once in a while, you
will skip the first whirlpool & have to move the other way to avoid the second.
don't say i didn't warn you!!!!!

---------------------------------------
  ROOM #11:  THE GIDDY GOONS (PURPLE WITH bent swords) room

movement -- s-r-f
  (H) -- SWORD FIRST ONLY ONCE!  GO RIGHT AND SWORD AGAIN.  BE SURE ONLY TO
SWING ONCE.

---------------------------------------
  ROOM #12:  THE LIZARD KING, WITH THE MAGNETIC GOLD URN.

  MOVEMENT -- R-L-L-L-L-L-F-S-(KEEP USING THE SWORD UNTIL HE IS KILLED)

  (H) -- FOR THE FIRST SEVEN MOVES WAIT UNTIL DIRK HAS STOPPED RUNNING TO MAKE
YOUR NEXT MOVE.  IF YOU TURN BEFORE DIRK GETS TO THE END OF THE PASSAGE BYE BYE!

---------------------------------------
  ROOM #13:  HEADLESS HORSEMAN RIDING TOWARDS YOU.

MOVEMENT -- L-L-R
  (H) -- MOVE ONLY AFTER YOU SEE THE HORSEMAN APPEAR.

---------------------------------------
ROOM #14: MAGICAL HORSE (TRIGGER)

MOVEMENT -- R-L-R-L-L-L
  (H) -- THE FIRST FIVE MOVES SHOW YOU RIDING DIRECTLY AT A PILLAR.  JUST BEFORE
YOU CONTACT THE PILLAR ONE SIDE WILL BURST INTO FLAMES.  MOVE TO THE OTHER SIDE
USING THE MOVEMENT PATTERN AS SOON AS YOU SEE THE FLAMES TIMING IS CRITICAL.

  (R) -- THE ROOM CAN BE REVERSED THUS CHANGING EVERY MOVE IN THIS ROOM.  YOU
CAN TELL IF IT IS REVERSED OR NOT BY WATCHING WHAT DIRECTION TRIGGER IS FACING
WHEN DIRK MOUNTS HIM IF TRIGGER IS FACING LEFT IT IS NORMAL, IF HE IS FACING
RIGHT IT IS REVERSED.

---------------------------------------
ROOM #15: THE TILT ROOM.

MOVEMENT -- B-F-L
  (H) -- MOVE BACKWARDS WHEN THE ROOM IS RECOGNIZED.  THEN WAIT FOR DIRK TO
SPLIT HIS FEET TO BALLANCE ON TWO TILES THEN MOVE FORWARD QUICKLY AND THEN
QUICKLY MOVE TO THE LEFT (TIMING IS AGAIN CRITICAL).

---------------------------------------
ROOM #16: THE BLACK KNIGHT ROOM

MOVEMENT -- R-L-F-L-R-L-R
  (H) -- THIS IS A VERY DIFFICULT ROOM FOR MOST PLAYERS.  THE FIRST 4 MOVES YOU
MAY WANT TO KEEP MOVING OVER AGAIN BECAUSE YOU WILL GET A "BUZZ" FOR A WHILE ON
THEM FOR A WHILE AS IT MAKES YOU WAIT FOR YOUR NEXT MOVE.  HOWEVER, THE LAST TWO
MOVES REQUIRE YOU TO MAKE YOUR NEXT MOVE WHILE DIRK IS IN THE AIR.  THIS WILL
TAKE A LITTLE PRACTICE BUT BE PATIENT, IT'S ALL WORTH IT.

  (R) -- DEFYING US EVEN MORE, THE PROGRAMMERS HAVE DECIDED THAT THIS ROOM MAY
ALSO BE REVERSED.  THIS PROVES TO BE A REAL CHALLENGE TO LEARNING PLAYERS.  IT
IS VERY DIFFICULT TO CATCH THE POINTER TO THE REVERSE YOUR FIRST FEW TIMES BUT
BEAR WITH IT, YOU'LL GET IT SOMEDAY...  TO TELL IF THE SCREEN IS REVERSED, YOU
MUST WATCH THE FIRST ENERGY BOLT THE KNIGHT SENDS AT YOU.  IT WILL COME AT YOU
AND SURROUND YOU ON THREE SIDES, THE SIDE WHICH IS OPEN IS EITHER THE LEFT OR
RIGHT SIDE.  IF IT IS THE RIGHT SIDE, THE SCREEN IS NORMAL, IF IT IS THE LEFT
SIDE THE SCREEN IS REVERSED.  (GOOD LUCK...  YOU'LL NEED IT...)

---------------------------------------
ROOM #17: THE ANIMATED WEAPONS ROOM.

MOVEMENT -- S-S-L-S-S
  (H) -- THE SWORDING IN THIS ROOM IS THE KEY.	THE BEST POINTER TO WHEN TO
SWING IS WHEN THE WEAPON CONFRONTING YOU STARTS DOWN AT YOU TO PRESS THE SWORD
BUTTON.  IT WOULD BE VERY BENEFICIAL TO WATCH OTHERS DO THIS TO GET THE IDEA.
MOVE LEFT TO AVOID THE ANVIL AS SOON AS YOU SEE IT.  WHEN DIRK ENCHANTS HIS
SWORD AND THE SMYTHE COMES TO LIFE PRESS SWORD AGAIN BEFORE HE BEGINS TO SWING.
NOTE THAT DIRK CLIMBS UP TO THE POT AUTOMATICALLY AND YOU NEEDENT MOVE FOR-
WARD.

  (R) -- THIS ROOM CAN BE REVERSED AND THE ONLY DIFFERENCE IS THAT HE MOVES
RIGHT TO AVOID THE ANVIL THIS TIME.  YOU CAN TELL WHICH WAY TO MOVE AT THIS
POINT BECAUSE FIRE IS ON THE SIDE THAT YOU SHOULD NOT MOVE TO.	ANOTHER POINTER
IS THAT DIRK IS ON THE LEFT SIDE OF THE SCREEN WHEN YOU SHOULD MOVE LEFT AND THE
RIGHT SIDE WHEN YOU SHOULD MOVE RIGHT.

---------------------------------------
  ROOM 18:  SPINNER ROOM WITH GRUNTS (GRUNTS?!"?)

MOVEMENT -- F-S-B-F
  (H) -- YOU ARE SHOWN TWO SPINNERS AND DIRK ATTEMPTING TO PASS THROUGH THEM.
THERE ARE TWO SEPERATE VERSIONS (ALTHOUGH THEY LOOK THE SAME, THEY ARE DIFFERENT
AND YOU MUST PASS BOTH TO GET TO THE DRAGON) BUT BOTH USE THE SAME SOLUTION.  AS
DIRK APPROACHES THE SPINNERS, HE WILL GRUNT ALOUD AS HE WALKS LIKE "UUUHHH",
"UOOOHEH".  WAIT FOR THE SECOND GRUNT AND THEN MOVE FORWARD.  IF YOU DO IT RIGHT
HE WILL SPRINT THROUGH AND JUMP FORWARD.  PRESS SWORD AS HE JUMPS, PULL BACK AND
WAIT FOR THE VIEW TO SWITCH.  FINALLY PUSH FORWARD AND HE WILL EXIT.

---------------------------------------
  ROOM #19:  THE LAVA MONSTERS (MUDHENS)

MOVEMENT -- S-F-F-F-ECT..ECT..
  (H) -- PRESS SWORD AND WAIT FOR HIM TO SWING AND CATCH HIS SWORD.  THEN MOVE
FORWARD QUICKLY OVER AND OVER.	IN THE WHOLE ROOM ONLY ONE MOVE MUST BE TIMED.
YOU RUN OUT ONTO THE END OF A PROJECTION AND MUST JUMP ACROSS A LAVA PIT TO THE
OTHER SIDE.  WAIT FOR THE OPPOSITE SIDE TO FLASH AND THEN JUMP.  AFTER THAT JUMP
CONTINUE MOVING FORWARD QUICKLY UNTIL YOU EXIT THE ROOM.

---------------------------------------
  ROOM #20:  THE ELECTRIFIED GROUND WITH A STEEL DOOR SLAMMING IN FRONT OF DIRK.

MOVEMENT -- F-L
  (H) -- MOVE FORWARD OVER AND OVER UNTIL DIRK MAKES IT THRU THE DOOR AS YOU
ONLY HAVE A SPLIT SECOND TO MAKE THE MOVE AND YOUR CHANCES ARE GOOD IF YOU KEEP
MOVING THE JOYSTICK FORWARD.  THEN DO THE SAME FOR THE LEFT AS THE SAME
CIRCUMSTANCES ARE PRESENT.

---------------------------------------
  ROOM #21:  ROOM WITH THE SQUARE POOL AND CRUMBLING FOUNDATION.

MOVEMENT -- L-F-R-F-L-F-S-R-F
  (H) -- THE FIRST MOVE MUST BE MADE QUICKLY AND YOU MUST BE VERY QUICK TO
DECIDE IF THE ROOM HAS BEEN REVERSED.  ALL THE MOVES REQUIRE YOU TO RESPOND AS
SOON AS THE LAST MOVE TAKES EFFECT.  WHEN YOU SWORD THE SPIDER AS SOON AS YOUR
SWORD CONTACTS HIM GO RIGHT AND THEN KEEP GOING FORWARD UNTIL DIRK IS SAFELY
OUT.

  (R) -- TO DETERMINE WHICH WAY TO GO AT THIS ROOM YOU MUST RECOGNIZE IT QUICKLY
AND LOOK AT ONE THING.	DIRK IS WEARING A SWORD ON ONE SIDE OF HIMSELF.  THAT IS
THE SIDE YOU SHOULD JUMP TO ALL OTHER MOVES MUST BE ADJUSTED ACCORDINGLY.  THE
NORMAL SCREEN HAS HIS SWORD ON THE LEFT SIDE.

---------------------------------------
  ROOM #22:  THE ROOM WITH STAIRS GOING TO THE LEFT AND BATS THAT ATTACK.

MOVEMENT -- S-L-L-S-L
  (H) -- PRESS SWORD QUICKLY.  MOVE LEFT.  WAIT FOR FLASH AND MOVE LEFT AGAIN.
REST IS ELEMENTARY.

---------------------------------------
  ROOM #23:  ROOM WITH CRUMBLING PATHS IN CAVERN WITH BATS.

MOVEMENT -- F-F-S-R-R
  (H) -- BE SURE YOU HAVE RIGHT ROOM BECAUSE LAST TWO ARE MUCH ALIKE IN
DESCRIPTION.  ON THIS ROOM GO FORWARD UNTIL SCREEN SWITCHES.  SWORD THE BATS AND
GO RIGHT.  AS SOON AS YOU LAND GO RIGHT AGAIN.

---------------------------------------
ROOM #24: THE CRYSTAL BALL ROOM.

MOVEMENT: R-F-R-R
  (H) -- MAKE FIRST 3 MOVES QUICK.  AFTER THRONE ROTATES AND SCREEN SWITCHES GO
RIGHT AGAIN AND DIRK WILL EXIT.

---------------------------------------
  ROOM #25:  ROOM WITH POT IN THE MIDDLE.

MOVEMENT -- F-S-B-S-R
  (H) -- MOVE FORWARD.	WAIT FOR TOUNGE TO GRAB YOUR ARM.  SWING.  MOVE BACK
QUICKLY AND SWING THEN EXIT STAGE RIGHT.

---------------------------------------
ROOM #26:  THE BOWLING BALL ROOM.

MOVEMENT -- B-B-B-B-B-B-F
  (H) -- YOU MUST MOVE DIRK TOWARDS YOU WHEN THE SMALL BALL THAT ROLLS DOWN FROM
THE SIDE PASSES IN FRONT OF YOU...  DO NOT WORRY..  MOVE ONLY AFTER THE SMALL
BALL HAS CLEARLY PASSED THE CENTER AND DIRK WILL RUN AND THE SCREEN WILL SWITCH.
WHEN DIRK IS IN THE PURPLE SCREEN BE AWARE THAT THAT IS THE LAST SCREEN AND THE
MOVE FORWARD IS NEXT...  MOVE FORWARD AS SOON AS THE SCREEN SWITCHES TO SHOW
DIRK STANDING BY A PIT....

---------------------------------------

*** SPECIAL ROOMS ***

THE ELEVATOR-

  TO FINISH THIS ROOM ALL YOU MUST DO IS JUMP OFF ON ONE OF THE THREE LANDINGS
THAT WILL APPEAR ON THE LEFT SIDE OF THE SCREEN.  THERE IS NO FOURTH LEVEL SO
TAKE YOUR PICK, IT MAKES NO DIFFERENCE WHICH YOU CHOOSE.  YOU MUST JUMP WHEN THE
PLATFORM SLOWS AND GIVES YOU A SECOND TO COMPLETE THE JUMP.  NOTE THAT YOU MUST
COMPLETE THIS ROOM MANY TIMES BEFORE GETTING TO THE DRAGON...

  ANOTHER IMPORTANT THING IS THAT YOU MUST ALSO COMPLETE THE SCREEN WHILE IT IS
REVERSED ONCE.	WHEN REVERSED YOU HAVE nine LEVELS TO CHOOSE FROM.  Three GROUPS
OF THREE, two GROUPs ON THE RIGHT AND ONE group ON THE LEFT.

  YOU CAN TELL IF THE SCREEN IS REVERSED BY WATCHING DIRK.  WHEN HE FIRST JUMPES
ONTO THE PLATFORM HE IS NORMALLY FACING RIGHT.	IF HE IS FACING LEFT IT IS
REVERSED.

---------------------------------------
D R A G O N S	L A I R ! ! !

MOVEMENT -- L-L-L-B-L-R-R-F-S-??????
  (H) -- ITS FUN TO DO A LITTLE ON YOUR OWN..  IF YOU REALLY GET STUCK DROP ME A
LETTER THRU THIS BBS...

  NOTE:  THE BEGINNING SECTION ON AUDIBLE SOUNDS GENERATED FROM YOUR JOYSTICK
MOVEMENTS IS VERY IMPORTANT.  BE SURE YOU HEAR A "BEEP" OR YOU'LL BE SORRY

	      HAVE A GREAT TIME
	      --- THE IRISH ROGUE


  address all correspondence to me and send e-mail if you have any questions or
are unsure about anything.  if you have a new solution or a neat feature you
would like to share, please post in the adventure hints hall...

  special note--- i have only been exposed to machines that are set on the
"easy" mode of play if the machines in my area are changed and significant
variations occur, i will post an addendum to this document.


=-=-=-= The Realm Of The Rogues =-=-=-=
	    (415)  941-1990
