# makefile for Fido
#
CFLAGS= -O 

CC      = cc -c
LD      = cc		# Link command
LDFLAGS	=
CPP     = $(CC) -E
DBG	= -O
ASM	= $(CC)	-c		# Assembler command

# Duh sore-ces

OBJS =	fido.o load_machine.o string.o

default:	$(OBJS)
		$(LD) -o fido $(OBJS) $(LDFLAGS)

fido.o :	fido.c fido.h
	$(CC) fido.c

load_machine.o : load_machine.c fido.h
	$(CC) load_machine.c

string.o : string.c
	$(CC) string.c
